import { getEventAssumption } from '../engine/event-assumptions.js';

/* The briefing text generator, kept free of React so it can run in node.

   server/scripts/archive-briefing.mjs generates the daily briefing with this
   exact function against the exported snapshot, so an archived briefing and
   the one the dashboard renders live cannot diverge. */
export function briefingText(model, scenario, data, engine) {
  const { STAGES, COMPANIES, COUNTRY_NAMES, EVENTS } = data;
  const { STAGE_BY_ID, eventField, operationalIndex, toDisplayIndex, companyContribution, companyVulnerability, STRUCTURAL_VULNERABILITY } = engine;
  const { scenarioActive, activeField, baselineField, stageDelta, countryDelta, countriesBase, countriesActive, datasetAsOf, modelVersion } = model;

  const evRows = EVENTS.map((e) => {
    const assumption = getEventAssumption(e.id);
    const { field } = eventField(e);
    const ownIndex = toDisplayIndex(operationalIndex(field));
    return { e, assumption, ownIndex };
  }).sort((a, b) => Math.abs(b.ownIndex - 5) - Math.abs(a.ownIndex - 5));

  const stageRows = STAGES.map((s) => ({
    s,
    metric: scenarioActive ? stageDelta[s.id] : activeField[s.id],
    structural: STRUCTURAL_VULNERABILITY[s.id],
  })).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 4);

  const companyRows = COMPANIES.map((c) => {
    const metric = scenarioActive
      ? companyContribution(c, activeField) - companyContribution(c, baselineField)
      : companyContribution(c, activeField);
    return { c, metric, vulnerability: companyVulnerability(c, activeField) };
  }).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 5);

  const countryRows = Object.entries(COUNTRY_NAMES).map(([id, name]) => ({
    id, name,
    metric: scenarioActive ? (countryDelta[id] ?? 0) : (countriesBase[id]?.operational ?? 0),
    structural: countriesBase[id]?.structural ?? 0,
  })).filter((r) => countriesBase[r.id]).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 4);

  const L = [];
  L.push("GP NEWS — SEMICONDUCTOR SUPPLY-CHAIN WATCH");
  L.push(`Dataset as of ${datasetAsOf} · generated by the SSCIM engine ${modelVersion} · sensitivity/comparison analysis, not a forecast`);
  L.push("");
  if (scenario?.event) {
    L.push(`*** ACTIVE SCENARIO: ${scenario.name.toUpperCase()} ***`);
    L.push(scenario.desc);
    L.push(`Scenario chain index: ${model.activeChainIndex.toFixed(2)} vs baseline ${model.baselineChainIndex.toFixed(2)} (Δ ${model.chainIndexDelta >= 0 ? "+" : ""}${model.chainIndexDelta.toFixed(2)}) [SCENARIO DELTA]`);
    L.push("");
  }
  L.push("WHAT CHANGED");
  if (scenario?.event) L.push(`• [ACTIVE SCENARIO] ${scenario.name} — ${scenario.desc}`);
  evRows.slice(0, 3).forEach(({ e, assumption, ownIndex }) => {
    const tag = assumption.operational ? "[OPERATIONAL]" : "[DISPLAYED, EXCLUDED FROM OPERATIONAL SCORE]";
    L.push(`• [${e.type}] ${e.title} — own-field index ${ownIndex.toFixed(2)} ${tag}, evidence: ${e.conf} (metadata only, not a magnitude multiplier).`);
    L.push(`  First-order: ${e.first}`);
    L.push(`  Second-order: ${e.second}`);
    if (!assumption.operational) L.push(`  Note: ${assumption.reason}`);
  });
  L.push("");
  L.push(scenarioActive ? "MOST-MOVED STAGES (SCENARIO DELTA)" : "MOST-AFFECTED STAGES (OPERATIONAL IMPACT)");
  stageRows.forEach(({ s, metric, structural }) =>
    L.push(`• ${s.name}: ${scenarioActive ? "Δ" : "impact"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · structural vulnerability ${structural.toFixed(1)}/10 [STRUCTURAL]`));
  L.push("");
  L.push(scenarioActive ? "COMPANY LEADERS (MARGINAL SCENARIO CONTRIBUTION)" : "COMPANY LEADERS (MODELED CONTRIBUTION)");
  companyRows.forEach(({ c, metric, vulnerability }) => {
    const via = Object.keys(c.stakes).map((sid) => STAGE_BY_ID[sid].name).slice(0, 2).join(", ");
    L.push(`• ${c.name} (HQ: ${COUNTRY_NAMES[c.country]}): ${scenarioActive ? "Δ contribution" : "contribution"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · vulnerability intensity ${vulnerability.toFixed(1)}/10 [OPERATIONAL, share-independent] via ${via}`);
  });
  L.push("");
  L.push(scenarioActive ? "COUNTRY BOARD (SCENARIO DELTA — not ranked by structural baseline)" : "COUNTRY BOARD (OPERATIONAL IMPACT)");
  countryRows.forEach(({ name, metric, structural }) =>
    L.push(`• ${name}: ${scenarioActive ? "Δ" : "impact"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · structural baseline ${structural.toFixed(2)}/10 [STRUCTURAL]`));
  L.push("");
  L.push("WATCH NEXT");
  evRows.slice(0, 3).forEach(({ e }) => L.push(`• ${e.watch}`));
  L.push("");
  L.push("METHOD (matches the published ⓘ Methodology documentation):");
  L.push("Structural vulnerability = weighted blend of network influence, geographic concentration (HHI+residual), policy exposure, substitutability, market sensitivity — time-invariant.");
  L.push("Operational impact = signed event propagation over ALL reachable graph paths (directional input-dependence / supplier-revenue-dependence proxies), decay(age,H)=2^(-age/H) with H=12 days from the frozen snapshot date, combined across simultaneous shocks via bounded noisy-OR (never Math.max, never unbounded sum).");
  L.push("Confidence (High/Medium/Low/Simulated) is evidence-quality metadata only — it is never multiplied into the impact magnitude.");
  L.push("Company vulnerability (share-independent) and contribution (share-weighted) are reported separately — market share does not cancel out of contribution.");
  L.push("This is a sensitivity/comparison analysis tool — not a calibrated, causal, or probabilistic forecast, and not investment advice. See MODEL_ROADMAP.md.");
  return L.join("\n");
}
