import { useState, useMemo } from 'react';
import { C } from '../theme.js';
import { useVault } from '../data/VaultContext.jsx';
import { getEventAssumption } from '../engine/event-assumptions.js';
import { useModalA11y } from './useModalA11y.js';

/* ================= GP News briefing generator =================
   Ranks stages/companies/countries by marginal SCENARIO DELTA when a
   scenario is active, and by current baseline operational impact
   otherwise (MISSION defect #3/#2 fix) — it always states which of the
   three metric families (structural / operational / scenario-delta) a
   given number is, includes the active scenario in "WHAT CHANGED", and
   never lets confidence act as a multiplier — it's reported as metadata
   only. */
export function briefingText(model, scenario, data, engine) {
  const { STAGES, COMPANIES, COUNTRY_NAMES, EVENTS } = data;
  const { STAGE_BY_ID, eventField, operationalIndex, toDisplayIndex, companyContribution, companyVulnerability, STRUCTURAL_VULNERABILITY } = engine;
  const { scenarioActive, activeField, baselineField, stageDelta, countryDelta, countriesBase, countriesActive, datasetAsOf, modelVersion } = model;

  const evRows = EVENTS.map((e) => {
    const assumption = getEventAssumption(e.id);
    const { field } = eventField(e);
    const ownIndex = toDisplayIndex(operationalIndex(field));
    return { e, assumption, ownIndex };
  }).sort((a, b) => Math.abs(b.ownIndex - 5) - Math.abs(a.ownIndex - 5));

  const stageRows = STAGES.map((s) => ({
    s,
    metric: scenarioActive ? stageDelta[s.id] : activeField[s.id],
    structural: STRUCTURAL_VULNERABILITY[s.id],
  })).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 4);

  const companyRows = COMPANIES.map((c) => {
    const metric = scenarioActive
      ? companyContribution(c, activeField) - companyContribution(c, baselineField)
      : companyContribution(c, activeField);
    return { c, metric, vulnerability: companyVulnerability(c, activeField) };
  }).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 5);

  const countryRows = Object.entries(COUNTRY_NAMES).map(([id, name]) => ({
    id, name,
    metric: scenarioActive ? (countryDelta[id] ?? 0) : (countriesBase[id]?.operational ?? 0),
    structural: countriesBase[id]?.structural ?? 0,
  })).filter((r) => countriesBase[r.id]).sort((a, b) => Math.abs(b.metric) - Math.abs(a.metric)).slice(0, 4);

  const L = [];
  L.push("GP NEWS — SEMICONDUCTOR SUPPLY-CHAIN WATCH (RESEARCH PROTOTYPE)");
  L.push(`Frozen demonstration snapshot as of ${datasetAsOf} · generated by the SSCIM engine ${modelVersion} · sensitivity/comparison tool, not a forecast`);
  L.push("");
  if (scenario?.event) {
    L.push(`*** ACTIVE SCENARIO: ${scenario.name.toUpperCase()} ***`);
    L.push(scenario.desc);
    L.push(`Scenario chain index: ${model.activeChainIndex.toFixed(2)} vs baseline ${model.baselineChainIndex.toFixed(2)} (Δ ${model.chainIndexDelta >= 0 ? "+" : ""}${model.chainIndexDelta.toFixed(2)}) [SCENARIO DELTA]`);
    L.push("");
  }
  L.push("WHAT CHANGED");
  if (scenario?.event) L.push(`• [ACTIVE SCENARIO] ${scenario.name} — ${scenario.desc}`);
  evRows.slice(0, 3).forEach(({ e, assumption, ownIndex }) => {
    const tag = assumption.operational ? "[OPERATIONAL]" : "[DISPLAYED, EXCLUDED FROM OPERATIONAL SCORE]";
    L.push(`• [${e.type}] ${e.title} — own-field index ${ownIndex.toFixed(2)} ${tag}, evidence: ${e.conf} (metadata only, not a magnitude multiplier).`);
    L.push(`  First-order: ${e.first}`);
    L.push(`  Second-order: ${e.second}`);
    if (!assumption.operational) L.push(`  Note: ${assumption.reason}`);
  });
  L.push("");
  L.push(scenarioActive ? "MOST-MOVED STAGES (SCENARIO DELTA)" : "MOST-AFFECTED STAGES (OPERATIONAL IMPACT)");
  stageRows.forEach(({ s, metric, structural }) =>
    L.push(`• ${s.name}: ${scenarioActive ? "Δ" : "impact"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · structural vulnerability ${structural.toFixed(1)}/10 [STRUCTURAL]`));
  L.push("");
  L.push(scenarioActive ? "COMPANY LEADERS (MARGINAL SCENARIO CONTRIBUTION)" : "COMPANY LEADERS (MODELED CONTRIBUTION)");
  companyRows.forEach(({ c, metric, vulnerability }) => {
    const via = Object.keys(c.stakes).map((sid) => STAGE_BY_ID[sid].name).slice(0, 2).join(", ");
    L.push(`• ${c.name} (HQ: ${COUNTRY_NAMES[c.country]}): ${scenarioActive ? "Δ contribution" : "contribution"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · vulnerability intensity ${vulnerability.toFixed(1)}/10 [OPERATIONAL, share-independent] via ${via}`);
  });
  L.push("");
  L.push(scenarioActive ? "COUNTRY BOARD (SCENARIO DELTA — not ranked by structural baseline)" : "COUNTRY BOARD (OPERATIONAL IMPACT)");
  countryRows.forEach(({ name, metric, structural }) =>
    L.push(`• ${name}: ${scenarioActive ? "Δ" : "impact"} ${metric >= 0 ? "+" : ""}${metric.toFixed(3)} [${scenarioActive ? "SCENARIO DELTA" : "OPERATIONAL"}] · structural baseline ${structural.toFixed(2)}/10 [STRUCTURAL]`));
  L.push("");
  L.push("WATCH NEXT");
  evRows.slice(0, 3).forEach(({ e }) => L.push(`• ${e.watch}`));
  L.push("");
  L.push("METHOD (matches the ⓘ Methodology overlay exactly):");
  L.push("Structural vulnerability = weighted blend of network influence, geographic concentration (HHI+residual), policy exposure, substitutability, market sensitivity — time-invariant.");
  L.push("Operational impact = signed event propagation over ALL reachable graph paths (directional input-dependence / supplier-revenue-dependence proxies), decay(age,H)=2^(-age/H) with H=12 days from the frozen snapshot date, combined across simultaneous shocks via bounded noisy-OR (never Math.max, never unbounded sum).");
  L.push("Confidence (High/Medium/Low/Simulated) is evidence-quality metadata only — it is never multiplied into the impact magnitude.");
  L.push("Company vulnerability (share-independent) and contribution (share-weighted) are reported separately — market share does not cancel out of contribution.");
  L.push("This is a sensitivity/comparison tool over a curated demonstration snapshot — not a calibrated, causal, or probabilistic forecast, and not investment advice. See MODEL_ROADMAP.md.");
  return L.join("\n");
}

export default function Briefing({ onClose, model, scenario }) {
  const { data, engine } = useVault();
  const [copied, setCopied] = useState(false);
  const text = useMemo(() => briefingText(model, scenario, data, engine), [model, scenario, data, engine]);
  const copy = () => {
    try { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch (e) {}
  };
  const { ref, onKeyDown } = useModalA11y(onClose);
  return (
    <div onClick={onClose} role="dialog" aria-modal="true" aria-label="GP News daily briefing" onKeyDown={onKeyDown} style={{ position: "fixed", inset: 0, background: "rgba(6,9,16,.85)", zIndex: 1200, display: "flex", alignItems: "center", justifyContent: "center", padding: 16 }}>
      <div ref={ref} tabIndex={-1} onClick={(e) => e.stopPropagation()} style={{ background: C.panel2, border: `1px solid ${C.copper}`, borderRadius: 8, maxWidth: 680, width: "100%", maxHeight: "85vh", display: "flex", flexDirection: "column", padding: "16px 18px", color: C.text, outline: "none" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, gap: 8, flexWrap: "wrap" }}>
          <h3 style={{ margin: 0, fontSize: 15 }}>GP News — Daily Briefing (auto-generated, research prototype)</h3>
          <div style={{ display: "flex", gap: 6 }}>
            <button onClick={copy} style={{ background: C.copper, color: "#0C111C", border: "none", borderRadius: 4, padding: "4px 12px", cursor: "pointer", fontFamily: "inherit", fontWeight: 700, fontSize: 12 }}>
              {copied ? "Copied ✓" : "Copy"}
            </button>
            <button onClick={() => { const b = new Blob([text], { type: "text/plain" }); const a = document.createElement("a"); a.href = URL.createObjectURL(b); a.download = "gp-briefing.txt"; a.click(); URL.revokeObjectURL(a.href); }}
              style={{ background: "transparent", border: `1px solid ${C.copper}`, color: C.copper, borderRadius: 4, padding: "4px 12px", cursor: "pointer", fontFamily: "inherit", fontSize: 12 }}>
              Download .txt
            </button>
            <button onClick={onClose} style={{ background: "transparent", border: `1px solid ${C.line}`, color: C.dim, borderRadius: 4, padding: "4px 10px", cursor: "pointer", fontFamily: "inherit", fontSize: 12 }}>Close</button>
          </div>
        </div>
        <pre className="mono" style={{ margin: 0, overflowY: "auto", fontSize: 11, lineHeight: 1.65, color: C.text, whiteSpace: "pre-wrap", background: C.panel, border: `1px solid ${C.line}`, borderRadius: 6, padding: "12px 14px" }}>{text}</pre>
        <div className="mono" style={{ fontSize: 9.5, color: C.faint, marginTop: 8 }}>
          Sensitivity/comparison tool over a frozen demonstration snapshot — not a calibrated forecast. Switch scenarios and regenerate to see the scenario delta ranking.
        </div>
      </div>
    </div>
  );
}
