import { useState, useMemo } from 'react';
import { C } from '../theme.js';
import { useVault } from '../data/VaultContext.jsx';
import { riskLabel } from '../utils/colors.js';

/* ================= GP News briefing generator — the commercial output ================= */
export function briefingText(model, scenario, data, engine) {
  const { STAGES, COMPANIES, COUNTRY_NAMES, EVENTS } = data;
  const { IMP_RANK, STAGE_BY_ID, chainImpact, eventShock, companyExposure } = engine;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const evRanked = EVENTS.map((e) => ({ e, eii: chainImpact(eventShock(e)) })).sort((a, b) => b.eii - a.eii);
  const topStages = STAGES.map((s) => ({ s, sc: model.stages[s.id].score, sh: model.shock[s.id] }))
    .sort((a, b) => b.sh - a.sh).slice(0, 4);
  const topCo = COMPANIES.map((c) => ({ c, exp: companyExposure(c, model.shock) }))
    .sort((a, b) => b.exp - a.exp).slice(0, 5);
  const topCountries = Object.entries(model.countries).sort((a, b) => b[1].score - a[1].score).slice(0, 4);
  const L = [];
  L.push("GP NEWS — SEMICONDUCTOR SUPPLY-CHAIN WATCH");
  L.push(`${today} · generated by the SSCIM engine · sample data`);
  L.push("");
  if (scenario?.event) {
    L.push(`*** SCENARIO BRIEFING: ${scenario.name.toUpperCase()} ***`);
    L.push(scenario.desc);
    L.push("");
  }
  L.push("WHAT CHANGED");
  evRanked.slice(0, 3).forEach(({ e, eii }) => {
    L.push(`• [${e.type}] ${e.title} — chain impact ${eii.toFixed(2)}, confidence ${e.conf}.`);
    L.push(`  First-order: ${e.first}`);
    L.push(`  Second-order: ${e.second}`);
  });
  L.push("");
  L.push("MOST-SHOCKED SUPPLY-CHAIN NODES");
  topStages.forEach(({ s, sc, sh }) =>
    L.push(`• ${s.name}: risk ${sc.toFixed(1)} (${riskLabel(sc)}), live shock ${sh.toFixed(1)}, importance rank #${IMP_RANK.indexOf(s.id) + 1}/24`));
  L.push("");
  L.push("COMPANY EXPOSURE LEADERS (footprint-weighted)");
  topCo.forEach(({ c, exp }) => {
    const via = Object.keys(c.stakes).map((sid) => STAGE_BY_ID[sid].name).slice(0, 2).join(", ");
    L.push(`• ${c.name} (${COUNTRY_NAMES[c.country]}): exposure ${exp.toFixed(1)} via ${via}`);
  });
  L.push("");
  L.push("COUNTRY RISK BOARD");
  topCountries.forEach(([id, c]) => L.push(`• ${COUNTRY_NAMES[id]}: ${c.score.toFixed(2)} ${riskLabel(c.score)}`));
  L.push("");
  L.push("WATCH NEXT");
  evRanked.slice(0, 3).forEach(({ e }) => L.push(`• ${e.watch}`));
  L.push("");
  L.push("METHOD: risk = 0.25·chokepoint(graph) + 0.20·concentration(HHI) + 0.20·policy(DB) + 0.15·substitutability + 0.10·shock(engine) + 0.10·market. Shock decays exp(−days/12), propagates on value-weighted edges.");
  L.push("All figures derive from curated sample data. Descriptive analysis only — not investment advice.");
  return L.join("\n");
}

export default function Briefing({ onClose, model, scenario }) {
  const { data, engine } = useVault();
  const [copied, setCopied] = useState(false);
  const text = useMemo(() => briefingText(model, scenario, data, engine), [model, scenario, data, engine]);
  const copy = () => {
    try { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch (e) {}
  };
  return (
    <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "rgba(6,9,16,.85)", zIndex: 1200, display: "flex", alignItems: "center", justifyContent: "center", padding: 16 }}>
      <div onClick={(e) => e.stopPropagation()} style={{ background: C.panel2, border: `1px solid ${C.copper}`, borderRadius: 8, maxWidth: 680, width: "100%", maxHeight: "85vh", display: "flex", flexDirection: "column", padding: "16px 18px", color: C.text }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, gap: 8, flexWrap: "wrap" }}>
          <h3 style={{ margin: 0, fontSize: 15 }}>GP News — Daily Briefing (auto-generated)</h3>
          <div style={{ display: "flex", gap: 6 }}>
            <button onClick={copy} style={{ background: C.copper, color: "#0C111C", border: "none", borderRadius: 4, padding: "4px 12px", cursor: "pointer", fontFamily: "inherit", fontWeight: 700, fontSize: 12 }}>
              {copied ? "Copied ✓" : "Copy"}
            </button>
            <button onClick={() => { const b = new Blob([text], { type: "text/plain" }); const a = document.createElement("a"); a.href = URL.createObjectURL(b); a.download = "gp-briefing.txt"; a.click(); URL.revokeObjectURL(a.href); }}
              style={{ background: "transparent", border: `1px solid ${C.copper}`, color: C.copper, borderRadius: 4, padding: "4px 12px", cursor: "pointer", fontFamily: "inherit", fontSize: 12 }}>
              Download .txt
            </button>
            <button onClick={onClose} style={{ background: "transparent", border: `1px solid ${C.line}`, color: C.dim, borderRadius: 4, padding: "4px 10px", cursor: "pointer", fontFamily: "inherit", fontSize: 12 }}>Close</button>
          </div>
        </div>
        <pre className="mono" style={{ margin: 0, overflowY: "auto", fontSize: 11, lineHeight: 1.65, color: C.text, whiteSpace: "pre-wrap", background: C.panel, border: `1px solid ${C.line}`, borderRadius: 6, padding: "12px 14px" }}>{text}</pre>
        <div className="mono" style={{ fontSize: 9.5, color: C.faint, marginTop: 8 }}>
          This is the product: the engine writes the briefing. Switch scenarios and regenerate to see scenario briefings.
        </div>
      </div>
    </div>
  );
}
