import { useMemo } from 'react';
import { C } from '../theme.js';
import { useVault } from '../data/VaultContext.jsx';
import { facilityProfile } from '../engine/facilityProfile.js';
import { facilityImpact, siteWeight } from '../engine/facilities.js';
import { facilityConnectivity } from '../engine/facilityNetwork.js';
import { fmtSigned, pct } from '../interaction/lensEncoding.js';
import { flagEmoji } from '../data/glossary.js';
import Logo from './Logo.jsx';
import Chip from './Chip.jsx';

/* ====================================================================
   FacilityDetail — the profile panel for one plant.

   Every section is generated by engine/facilityProfile.js from the same
   fields for all 244 sites, so two profiles differ only where the sites
   differ. Nothing here is hand-written per facility except the one-line
   `output` the record itself carries.

   Three things are kept visibly separate, because conflating them is how
   a site-level map starts lying:
     · what the site IS            — sourced identity and location
     · where it SITS in the model  — stage shares and network links, both
                                     modeled, both shares of a sample
     · what is happening TO it now — the operational field at its stages
   ==================================================================== */

const Row = ({ k, v }) => (
  <div style={{ display: 'flex', gap: 8, padding: '2px 0', borderBottom: `1px solid ${C.line}` }}>
    <span className="mono" style={{ fontSize: 9.5, letterSpacing: 0.6, color: C.faint, width: 118, flexShrink: 0 }}>{k}</span>
    <span style={{ fontSize: 11, color: C.text, lineHeight: 1.5 }}>{v}</span>
  </div>
);

export default function FacilityDetail({ facilityId, setSel, model }) {
  const { data, engine } = useVault();
  const { FACILITY_LAYER, FACILITY_NETWORK, COMPANY_BY_ID, COUNTRY_NAMES } = data;
  const { STAGE_BY_ID } = engine;

  const facility = FACILITY_LAYER.FACILITY_BY_ID[facilityId];

  const ctx = useMemo(
    () => ({ COMPANY_BY_ID, COUNTRY_NAMES, STAGE_BY_ID, layer: FACILITY_LAYER }),
    [COMPANY_BY_ID, COUNTRY_NAMES, STAGE_BY_ID, FACILITY_LAYER],
  );
  const profile = useMemo(() => (facility ? facilityProfile(facility, ctx) : null), [facility, ctx]);

  if (!facility || !profile) {
    return <div className="mono" style={{ fontSize: 11, color: C.faint }}>No modeled facility with id “{facilityId}”.</div>;
  }

  const conn = facilityConnectivity(FACILITY_NETWORK, facility.id);
  const edges = FACILITY_NETWORK?.linksByFacility?.[facility.id] || { inbound: [], outbound: [] };
  const impact = facilityImpact(facility, model?.activeField || {});
  const live = siteWeight(facility) > 0;

  const linkRow = (l, dir) => {
    const otherId = dir === 'out' ? l.to : l.from;
    const other = FACILITY_LAYER.FACILITY_BY_ID[otherId];
    if (!other) return null;
    return (
      <li key={`${dir}:${l.from}:${l.to}`} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '3px 6px', border: `1px solid ${C.line}`, borderRadius: 4, background: C.panel }}>
        <span aria-hidden style={{ fontSize: 10 }}>{flagEmoji(other.country)}</span>
        <button type="button" onClick={() => setSel({ type: 'facility', id: other.id })}
          style={{ flex: 1, textAlign: 'left', background: 'transparent', border: 'none', padding: 0, font: 'inherit', fontSize: 10.5, color: C.text, cursor: 'pointer', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
          {other.name}
        </button>
        <span className="mono" style={{ fontSize: 8.5, color: C.faint, whiteSpace: 'nowrap' }}>
          {/* the stage the OTHER end of the link occupies */}
          {(STAGE_BY_ID[dir === 'out' ? l.toStage : l.fromStage]?.name || '').slice(0, 16)}
        </span>
        <span className="mono" style={{ fontSize: 9.5, color: C.copper, width: 34, textAlign: 'right' }}
          title="Strength relative to the strongest modeled link in the snapshot">{pct(l.rel ?? 0)}</span>
      </li>
    );
  };

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
        <span aria-hidden style={{ fontSize: 15 }}>{flagEmoji(facility.country)}</span>
        <h3 style={{ margin: 0, fontSize: 15, lineHeight: 1.3 }}>{facility.name}</h3>
      </div>
      <div className="mono" style={{ fontSize: 9.5, letterSpacing: 1, color: C.copper, margin: '4px 0 8px' }}>
        {profile.headline.toUpperCase()}
      </div>

      <p style={{ margin: '0 0 10px', fontSize: 12.5, color: C.dim, lineHeight: 1.6 }}>{profile.intro}</p>

      {/* ---- what it is ---- */}
      <div className="mono" style={{ fontSize: 9, letterSpacing: 2, color: C.dim, margin: '0 0 4px' }}>PROFILE</div>
      <div style={{ marginBottom: 10 }}>
        {profile.facts.map(([k, v]) => (
          <Row key={k} k={k.toUpperCase()} v={k === 'Operator'
            ? (
              <button type="button" onClick={() => setSel({ type: 'company', id: facility.company })}
                style={{ display: 'inline-flex', alignItems: 'center', gap: 5, background: 'transparent', border: 'none', padding: 0, font: 'inherit', color: C.copper, cursor: 'pointer' }}>
                <Logo cid={facility.company} size={12} />{v}
              </button>
            )
            : v} />
        ))}
      </div>

      {/* ---- where it sits ---- */}
      <div className="mono" style={{ fontSize: 9, letterSpacing: 2, color: C.dim, margin: '0 0 4px' }}>
        STAGES FED · SHARE OF THAT STAGE&apos;S MODELED SITES
      </div>
      <div style={{ display: 'grid', gap: 2, marginBottom: 10 }}>
        {profile.stageRoles.map((r) => (
          <div key={r.stageId} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <button type="button" onClick={() => setSel({ type: 'stage', id: r.stageId })}
              style={{ flex: '0 0 150px', textAlign: 'left', background: 'transparent', border: 'none', padding: 0, font: 'inherit', fontSize: 11, color: C.text, cursor: 'pointer' }}>
              {r.stageName}
            </button>
            <div style={{ flex: 1, height: 5, background: C.panel, borderRadius: 3, overflow: 'hidden' }}>
              <div style={{ width: `${Math.min(100, r.share * 100)}%`, height: '100%', background: C.copper, opacity: 0.8 }} />
            </div>
            <span className="mono" style={{ fontSize: 10, width: 38, textAlign: 'right', color: live ? C.copper : C.faint }}>
              {live ? pct(r.share) : '—'}
            </span>
          </div>
        ))}
      </div>

      {/* ---- network ---- */}
      <div className="mono" style={{ fontSize: 9, letterSpacing: 2, color: C.dim, margin: '0 0 4px' }}>
        MODELED SITE-TO-SITE LINKS ({conn.degree})
      </div>
      {conn.degree === 0 ? (
        <div className="mono" style={{ fontSize: 10, color: C.faint, lineHeight: 1.6, marginBottom: 10 }}>
          No link in the modeled set touches this site. That happens when its operator has no customer edge in the
          sample, when no stage it feeds directly adjoins a customer&apos;s stage, or when its links fell outside the
          displayed cap — not necessarily that the site is unconnected in reality.
        </div>
      ) : (
        <div style={{ marginBottom: 10 }}>
          {edges.outbound.length > 0 && (
            <>
              <div className="mono" style={{ fontSize: 8.5, color: C.faint, margin: '2px 0 3px' }}>SUPPLIES →</div>
              <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 2 }}>
                {edges.outbound.slice(0, 6).map((l) => linkRow(l, 'out'))}
              </ul>
            </>
          )}
          {edges.inbound.length > 0 && (
            <>
              <div className="mono" style={{ fontSize: 8.5, color: C.faint, margin: '6px 0 3px' }}>← SUPPLIED BY</div>
              <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: 2 }}>
                {edges.inbound.slice(0, 6).map((l) => linkRow(l, 'in'))}
              </ul>
            </>
          )}
          <div className="mono" style={{ fontSize: 8.5, color: C.faint, marginTop: 5, lineHeight: 1.6 }}>
            A modeled link, not a shipment route: company-level supplier-revenue share × each site&apos;s share of its
            stage × the engine&apos;s input-dependence prior. The percentage is strength relative to the strongest
            modeled link in the snapshot — an ordering, not a volume. No dataset here records which plant ships to
            which plant.
          </div>
        </div>
      )}

      {/* ---- what is happening to it ---- */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginBottom: 8 }}>
        {facility.stages.map((sid) => <Chip key={sid} label={STAGE_BY_ID[sid]?.name} onClick={() => setSel({ type: 'stage', id: sid })} />)}
        <Chip label={COUNTRY_NAMES[facility.country]} onClick={() => setSel({ type: 'country', id: facility.country })} outline />
      </div>
      {impact !== 0 && (
        <div className="mono" style={{ fontSize: 10.5, color: C.amber }}>
          operational effect at this site&apos;s stages {fmtSigned(impact)}
        </div>
      )}

      <div className="mono" style={{ fontSize: 8.5, color: C.faint, marginTop: 8, lineHeight: 1.7 }}>
        {profile.caveats.map((c) => <div key={c} style={{ marginBottom: 2 }}>· {c}</div>)}
      </div>
    </div>
  );
}
