/* Headline citations behind the corrections applied in seed-data.js.
   Not exhaustive per-field — see README §8/§9 for the evidence-tier framework.
   scope uses "company:<id>", "stage:<id>", "customer:<supplier>-><customer>",
   or "owners:<id>" to key back to a specific data point. */
export const DATA_NOTES = [
  { scope: "stage:litho", tier: "B", note: "ASML ≈83-84% of lithography unit sales (2024-2025); on a revenue basis, materially higher given EUV's ASP premium over Nikon/Canon's DUV-only lineup. ASML holds 100% of EUV specifically.", source: "TrendForce 'ASML EUV Dominance' (2025-2026); ASML FY2025 20-F; Nikon/Canon FY2025 segment financials." },
  { scope: "company:tsmc", tier: "B", note: "TSMC ≈70% of total foundry revenue (Q4 2025), ~85-90%+ of leading-edge (<=7nm) capacity specifically.", source: "TrendForce press release 20260312-12965 (4Q25 Global Top 10 Foundries)." },
  { scope: "owners:intel", tier: "C", note: "U.S. government converted $8.9B of CHIPS Act/Secure Enclave funding into a 9.9% common-equity stake in Intel, Aug 2025; SoftBank ($2B) and Nvidia ($5B) also took new common-stock positions the same year.", source: "Intel 8-K filings (SEC EDGAR, Aug 18 & Sept 15 2025); NPR/CNBC/Manufacturing Dive, Aug 2025." },
  { scope: "customer:tsmc->nvidia", tier: "C", note: "Nvidia became TSMC's #1 customer in 2025 at 19% of revenue, overtaking Apple (17%, down from 22-25% in 2024).", source: "CNBC, 'Nvidia set to supplant Apple as TSMC's top customer' (2026-01-26); TSMC FY2025 customer disclosures." },
  { scope: "stage:hbm", tier: "B", note: "SK hynix ~52-55% of HBM (revenue/shipment blend); Samsung materially lower than the prior sample figure (~20-22%, trailed on HBM3E qualification); Micron the fastest riser (~23-25%, targeting 24%+ share by end-2025).", source: "Astute Group HBM market share note (2026); TrendForce Micron HBM coverage (2025-06-26); SK hynix 2026 Market Outlook." },
  { scope: "customer:skhynix->nvidia", tier: "B", note: "NVIDIA drove ~27% of SK hynix's total company revenue in 1H2025 (up from ~16% in 2024).", source: "TrendForce, 'NVIDIA Reportedly Drives 27% of SK hynix Revenue in 1H25' (2025-08-18)." },
  { scope: "company:ansys", tier: "A", note: "Ansys is no longer an independent EDA competitor — Synopsys completed its acquisition in 2025; Ansys revenue is now consolidated into Synopsys's reported figures.", source: "Synopsys FY2025 disclosures; SemiAnalysis EDA Market Primer (2025)." },
  { scope: "company:nvidia", tier: "B", note: "NVIDIA's share of the merchant AI-accelerator market is commonly cited around ~75-80% in 2025, well above the prior sample figure.", source: "Silicon Analysts, 'NVIDIA AI GPU Market Share 2024-2026'." },
  { scope: "company:cxmt", tier: "B", note: "CXMT (DRAM) and YMTC (NAND) are distinct Chinese memory makers previously merged into one model entry; CXMT is the fastest-growing name in the memory cluster (~7.7% global DRAM share, Q4 2025, rising).", source: "SemiAnalysis, 'China's CXMT Is Set to Challenge DRAM Incumbents' (2025-2026)." },
  { scope: "owners:tsmc", tier: "C", note: "Taiwan's National Development Fund is TSMC's largest single shareholder (~6.4%); GIC (Singapore) is a top-5 holder ahead of the previously modeled 'Capital Group' position.", source: "TSMC 2025 Annual Report; MarketScreener shareholder data (2025)." },
  { scope: "owners:foxconn", tier: "B", note: "Terry Gou's Foxconn stake is reported as mid-single-digit and declining; holding companies linked to his daughter disclosed disposing of all their Hon Hai shares in Dec 2025.", source: "Focus Taiwan / TWSE disclosure (2025-12-02)." },
  { scope: "customer:apple->foxconn", tier: "B", note: "Foxconn's cloud/AI-server segment overtook Apple-driven consumer electronics as its largest revenue segment for the first time in 2025.", source: "CRN Asia (Jan 2026); Hon Hai FY2025/Q1 2026 results." },
  { scope: "stage:m_ai", tier: "B", note: "US hyperscale AI-data-center concentration (~60%+) is understated by a flat 0.5/0.25 US/China split; China's real 2025-2026 AI capex is far smaller in absolute terms than any single US hyperscaler's guided 2026 capex.", source: "Dell'Oro/TrendForce/BloombergNEF data-center-spending trackers (late 2025/early 2026)." },
  { scope: "stage:adv_pkg", tier: "C", note: "SPIL has been a wholly-owned ASE Technology Holding subsidiary since 2018 — its output is already consolidated into ASE's reported financials; modeled here without an independent stake to avoid double-counting.", source: "ASE Technology Holding corporate structure disclosures." },
  { scope: "stage:memory_fab", tier: "B", note: "\"memory_fab\" models DRAM and NAND as one combined stage, but each company's earlier entry was its own single-segment (DRAM-only or NAND-only) share entered directly against that combined denominator — e.g. Kioxia (NAND-only) was carrying its ~14-16% NAND share as if it were a share of the combined market, and the modeled total summed to >100%. Corrected to a revenue-weighted blend of Q1 2026 DRAM shares (Samsung 38%, SK hynix 29%, Micron 22%, CXMT 8%, Nanya 2%) and NAND shares (Samsung 29%, SK hynix 18%, Kioxia 14%, Micron 13%, YMTC 13%), weighted by the real DRAM:NAND market-size split (~$129B:$65B, ~66.5%:33.5%). The ~4.5% left over is real (chiefly Western Digital/SanDisk's NAND share) but not modeled as its own company here, so it is carried as unmodeled residual rather than invented.", source: "Counterpoint Research, \"Global DRAM and HBM Market Share\" and \"Global NAND Memory Market Share\" (Q1 2026); Yole Group, \"Memory market surges beyond expectations: almost $200 billion in 2025 driven by HBM & AI\" (2025)." },
];
