/* ====================================================================
   HISTORY_EVENTS — real, sourced semiconductor-supply-chain events,
   Feb 2021 → Jun 2026, backfilled into the vault so the computed index
   history (app engine LONG_HISTORY) reflects how each shock moved the
   chain index at the time it happened.

   Curation rules (same contract as seed-data EVENTS):
   - `dateISO` is authoritative; `daysAgo` is DERIVED from it against
     DATASET_AS_OF at seed/backfill time (never hand-maintained).
   - sev is the event's magnitude on its own date (the engine's 12-day
     half-life decays it from there) — a 2021 event contributes ~0 to
     the CURRENT index by design; it shows up in the historical series.
   - Every id must also be classified in app/src/engine/
     event-assumptions.js (direction / channel / operational) — an
     unclassified id is displayed but excluded from the scored index.
   - stages/countries must reference existing vault ids (audit-enforced).
   ==================================================================== */

export const DATASET_AS_OF = '2026-07-06';

export function daysAgoOf(dateISO, asOf = DATASET_AS_OF) {
  return Math.round((Date.parse(asOf) - Date.parse(dateISO)) / 86400000);
}

export const HISTORY_EVENTS = [
  // ---------------- 2021 ----------------
  { id: 'h2102_uri', dateISO: '2021-02-16', date: 'Feb 16, 2021', sev: 6, type: 'Natural Disaster', conf: 'High',
    title: 'Winter Storm Uri shuts Texas fabs',
    summary: 'Grid failure forces Samsung Austin, NXP and Infineon to halt Texas fabs for weeks, deepening the auto-chip shortage.',
    stages: ['mature_fab', 'analog', 'm_auto'], countries: ['us'],
    first: 'Weeks of lost mature-node and analog output during an already severe shortage.',
    second: 'Auto OEM production cuts extend; lead times for MCUs and power parts lengthen further.',
    watch: 'Fab restart timelines · auto OEM shutdown announcements',
    detail: 'The February 2021 Texas grid failure took Samsung Austin, NXP and Infineon fabs offline; full recovery took one to two months and removed material mature-node supply during the peak of the global chip shortage.',
    source: 'Company statements (Samsung, NXP, Infineon) + trade press',
    timeline: [['Feb 16, 2021', 'Austin-area fabs lose power and halt'], ['Mar–Apr 2021', 'Staged restart; full output recovery takes weeks']] },

  { id: 'h2103_renesas', dateISO: '2021-03-19', date: 'Mar 19, 2021', sev: 7, type: 'Industrial Accident', conf: 'High',
    title: 'Renesas Naka 300mm fab fire',
    summary: 'Fire in the N3 building destroys tools on a line supplying ~30% of Renesas auto MCUs.',
    stages: ['mature_fab', 'analog', 'm_auto'], countries: ['jp'],
    first: 'Auto MCU supply tightens sharply; ~3 months to restore full capacity.',
    second: 'OEMs idle lines globally; industry pushes multi-sourcing and safety stock for auto silicon.',
    watch: 'Renesas recovery milestones · auto OEM output guidance',
    detail: 'The March 2021 fire damaged 23 tools and cleanroom area on the Naka 300mm line; Renesas restored pre-fire shipment levels only around July 2021, compounding the automotive chip shortage.',
    source: 'Renesas official recovery updates + Nikkei/Reuters coverage',
    timeline: [['Mar 19, 2021', 'Fire in N3 building'], ['Apr 17, 2021', 'Production partially resumes'], ['Jul 2021', 'Shipments back to pre-fire levels']] },

  { id: 'h2108_malaysia', dateISO: '2021-08-23', date: 'Aug 23, 2021', sev: 6, type: 'Pandemic Disruption', conf: 'High',
    title: 'Malaysia lockdowns choke backend assembly',
    summary: 'Delta-wave factory closures hit OSAT and passives clusters (Melaka, Muar), stalling auto chip supply.',
    stages: ['osat', 'm_auto'], countries: ['my'],
    first: 'Backend assembly/test throughput drops; STMicro and Infineon backend sites disrupted.',
    second: 'Ford, GM, Toyota cut output citing Malaysia backend shortages; OSAT geographic concentration exposed.',
    watch: 'Malaysia workforce caps · OSAT utilization recovery',
    detail: 'Malaysia handled roughly 13% of global chip assembly/test; recurring COVID closures through Q3 2021 (including STMicroelectronics Muar) forced automaker production cuts worldwide.',
    source: 'Company disclosures + national COVID policy record + trade press',
    timeline: [['Jun–Aug 2021', 'Rolling factory closures under lockdown'], ['Q4 2021', 'Gradual return to full workforce']] },

  // ---------------- 2022 ----------------
  { id: 'h2202_kioxia', dateISO: '2022-02-10', date: 'Feb 10, 2022', sev: 6, type: 'Industrial Accident', conf: 'High',
    title: 'Kioxia/WD NAND contamination incident',
    summary: 'Material contamination at Yokkaichi/Kitakami scraps multiple exabytes of 3D NAND output.',
    stages: ['memory_fab', 'm_consumer'], countries: ['jp'],
    first: 'At least ~6.5 EB of NAND lost; contract prices jump double digits within weeks.',
    second: 'SSD makers hedge inventory; reinforces memory-supply fragility narrative.',
    watch: 'NAND contract pricing · Kioxia recovery statements',
    detail: 'Western Digital disclosed at least 6.5 exabytes of flash output lost to contaminated materials at the joint-venture fabs; NAND spot and contract prices rose sharply into Q2 2022.',
    source: 'Western Digital/Kioxia disclosures + TrendForce pricing data',
    timeline: [['Feb 10, 2022', 'Contamination disclosed'], ['Q2 2022', 'Output normalizes; prices stay elevated a quarter']] },

  { id: 'h2202_neon', dateISO: '2022-02-24', date: 'Feb 24, 2022', sev: 7, type: 'Critical Material Risk', conf: 'High',
    title: 'Ukraine war cuts semiconductor neon supply',
    summary: 'Invasion halts Ingas and Cryoin, which supplied roughly half of semiconductor-grade neon for lithography lasers.',
    stages: ['gases', 'litho'], countries: ['tw', 'kr', 'us', 'jp'],
    first: 'Neon spot prices spike ~10x; chipmakers lean on stockpiles and recycling.',
    second: 'Gas sourcing diversifies (China share rises); no major fab halt but buffer inventories drain.',
    watch: 'Neon spot pricing · fab inventory disclosures',
    detail: 'Ukrainian purifiers Ingas (Mariupol) and Cryoin (Odesa) halted with the February 2022 invasion; fabs avoided stoppages via 6–12 month stockpiles, but neon prices rose an order of magnitude and sourcing shifted to Chinese suppliers.',
    source: 'Reuters supplier reporting + TECHCET gas-market analysis',
    timeline: [['Feb 24, 2022', 'Both major Ukrainian neon plants halt'], ['H2 2022', 'Recycling + new capacity ease the squeeze']] },

  { id: 'h2204_shanghai', dateISO: '2022-04-05', date: 'Apr 05, 2022', sev: 6, type: 'Pandemic Disruption', conf: 'High',
    title: 'Shanghai COVID lockdown snarls electronics logistics',
    summary: 'Two-month closed-loop lockdown disrupts assembly, packaging and port logistics across the Yangtze Delta.',
    stages: ['osat', 'substrates', 'm_consumer'], countries: ['cn'],
    first: 'Component shipments delayed; SMIC/Hua Hong run closed-loop while downstream assembly stalls.',
    second: 'Quanta/Pegatron laptop and Apple supplier output cut; port backlog ripples through Q3.',
    watch: 'Port throughput · closed-loop production announcements',
    detail: 'The April–May 2022 Shanghai lockdown kept wafer fabs running in closed loop but froze much of the packaging, assembly and freight layer around them; consumer-electronics output guidance was cut across the supply chain.',
    source: 'Company guidance (Pegatron, Quanta) + Shanghai municipal policy record',
    timeline: [['Apr 5, 2022', 'City-wide lockdown begins'], ['Jun 1, 2022', 'Lockdown formally lifts; backlog clears over the summer']] },

  { id: 'h2208_strait22', dateISO: '2022-08-04', date: 'Aug 04, 2022', sev: 6, type: 'Geopolitical Risk', conf: 'High',
    title: 'PLA live-fire exercises encircle Taiwan',
    summary: 'Post-Pelosi-visit exercises close airspace/sea zones around Taiwan for days; no fab disruption.',
    stages: ['adv_fab', 'adv_pkg', 'osat'], countries: ['tw', 'cn', 'us'],
    first: 'Shipping reroutes and insurance repricing; fabs unaffected.',
    second: 'Baseline Taiwan-concentration risk repriced; diversification pressure on leading-edge customers rises.',
    watch: 'Exercise frequency · war-risk insurance premia',
    detail: 'The August 2022 exercises were the largest around Taiwan in decades, briefly disrupting shipping lanes and flights; physical chip flows continued, making this a hazard-signal event rather than a realized supply shock.',
    source: 'Taiwan MND activity reports + shipping-data providers',
    timeline: [['Aug 2, 2022', 'Pelosi visit'], ['Aug 4–10, 2022', 'Live-fire exercise zones active']] },

  { id: 'h2208_chips', dateISO: '2022-08-09', date: 'Aug 09, 2022', sev: 4, type: 'Policy Signal', conf: 'High',
    title: 'U.S. CHIPS and Science Act signed',
    summary: '$52.7B in fab subsidies and R&D funding to rebuild U.S. manufacturing share.',
    stages: ['adv_fab', 'mature_fab', 'research'], countries: ['us'],
    first: 'Long-run capacity diversification signal; no near-term supply change.',
    second: 'Anchors TSMC Arizona, Samsung Taylor, Intel Ohio and Micron expansions; guardrails restrict recipients\' China expansion.',
    watch: 'Award announcements · fab construction milestones',
    detail: 'Signed August 9, 2022, the act funds $39B of manufacturing incentives plus R&D programs; its China guardrails also shape where subsidized capacity can be built for a decade.',
    source: 'Public Law 117-167 (official) + CHIPS Program Office awards',
    timeline: [['Aug 9, 2022', 'Signed into law'], ['2024–2025', 'Major awards finalized (TSMC, Samsung, Intel, Micron)']] },

  { id: 'h2210_bis', dateISO: '2022-10-07', date: 'Oct 07, 2022', sev: 9, type: 'Export Control', conf: 'High',
    title: 'BIS sweeping China export controls (Oct 7 rules)',
    summary: 'Unprecedented controls on advanced-computing chips, supercomputer end-uses, U.S.-person support and advanced-fab tooling for China.',
    stages: ['logic_ai', 'adv_fab', 'memory_fab', 'litho', 'depo', 'etch', 'metro'], countries: ['us', 'cn'],
    first: 'A100/H100-class exports cut off; U.S. toolmakers pull staff from Chinese advanced fabs; YMTC/CXMT roadmaps stall.',
    second: 'Defines the compute-containment regime every later rule extends; accelerates China\'s domestic-tool substitution drive.',
    watch: 'Allied alignment (NL/JP) · entity-list additions · Chinese fab tool orders',
    detail: 'The October 7, 2022 rules restricted advanced-node logic (<16/14nm), DRAM (<18nm half-pitch) and NAND (128L+) tooling and services for China, plus performance-threshold controls on AI accelerators — the broadest semiconductor export action since the Cold War.',
    source: 'BIS interim final rule 87 FR 62186 (official) + CSIS analysis',
    timeline: [['Oct 7, 2022', 'Interim final rule published'], ['Oct 12, 2022', 'U.S. toolmaker support suspensions begin'], ['Oct 2023', 'First major update tightens thresholds']] },

  // ---------------- 2023 ----------------
  { id: 'h2301_alliance', dateISO: '2023-01-27', date: 'Jan 27, 2023', sev: 5, type: 'Policy Signal', conf: 'Medium',
    title: 'U.S.–Japan–Netherlands align on tool controls',
    summary: 'Trilateral agreement (unannounced formally) to extend advanced-lithography and tool export restrictions to China.',
    stages: ['litho', 'depo', 'etch'], countries: ['us', 'nl', 'jp'],
    first: 'Signals ASML DUV and Nikon/TEL tools will come under national controls.',
    second: 'Closes the non-U.S. tooling gap in the Oct 7 regime; China accelerates stockpile buying ahead of effective dates.',
    watch: 'Dutch and Japanese implementing rules',
    detail: 'Reported January 27, 2023: the three governments agreed in principle to align export controls on semiconductor manufacturing equipment; implementing rules followed in mid-2023 in both countries.',
    source: 'Reuters/Bloomberg reporting on the agreement (no official text released)',
    timeline: [['Jan 27, 2023', 'Agreement reported'], ['Mar 31, 2023', 'Japan announces its measures'], ['Jun 30, 2023', 'Dutch licensing rule published']] },

  { id: 'h2307_gage', dateISO: '2023-07-03', date: 'Jul 03, 2023', sev: 7, type: 'Critical Material Risk', conf: 'High',
    title: 'China imposes gallium and germanium export licensing',
    summary: 'MOFCOM requires licenses for Ga/Ge exports from Aug 1, 2023 — first material-leverage response to chip controls.',
    stages: ['gases', 'analog'], countries: ['cn', 'jp', 'de', 'us'],
    first: 'Exports fall to near zero for two months; prices spike for compound-semi and power/RF inputs.',
    second: 'Non-China Ga/Ge sourcing projects restart; establishes the minerals-for-chips retaliation template.',
    watch: 'License approval rates · Ga/Ge spot prices',
    detail: 'Announced July 3, 2023 (effective August 1), the licensing regime covered gallium and germanium compounds central to power electronics, RF and photonics; August exports dropped to zero before licensed flows resumed at lower volumes.',
    source: 'MOFCOM Announcement No. 23 (official) + customs statistics',
    timeline: [['Jul 3, 2023', 'Controls announced'], ['Aug 1, 2023', 'Licensing effective; exports pause'], ['Q4 2023', 'Licensed exports resume below prior levels']] },

  { id: 'h2307_jpsme', dateISO: '2023-07-23', date: 'Jul 23, 2023', sev: 6, type: 'Export Control', conf: 'High',
    title: 'Japan tool export controls take effect',
    summary: '23 categories of semiconductor manufacturing equipment now require export licenses, aligning Japan with the U.S. regime.',
    stages: ['depo', 'etch', 'metro', 'litho', 'resist'], countries: ['jp', 'cn'],
    first: 'TEL, Nikon, Screen and peers need licenses for advanced-node tool sales to China.',
    second: 'Chinese fabs pre-bought heavily in H1 2023; Japanese SME China revenue stays high on legacy-node demand.',
    watch: 'METI license practice · Japanese SME China revenue mix',
    detail: 'Japan\'s METI measures, announced March 31 and effective July 23, 2023, cover cleaning, deposition, lithography, etch and inspection equipment for advanced nodes — closing much of the non-U.S. tooling route into Chinese leading-edge fabs.',
    source: 'METI ordinance (official) + company disclosures',
    timeline: [['Mar 31, 2023', 'Measures announced'], ['Jul 23, 2023', 'Licensing effective']] },

  { id: 'h2308_mate60', dateISO: '2023-08-29', date: 'Aug 29, 2023', sev: 5, type: 'Technology Update', conf: 'High',
    title: 'Huawei Mate 60 Pro ships SMIC 7nm silicon',
    summary: 'Teardowns confirm a SMIC N+2 7nm Kirin 9000s made under export controls — a controls-effectiveness shock.',
    stages: ['adv_fab', 'logic_ai'], countries: ['cn', 'us'],
    first: 'Demonstrates DUV multi-patterning path to 7nm at scale despite tool restrictions.',
    second: 'Hardens U.S. political consensus for tighter rules (Oct 2023, Dec 2024 packages follow).',
    watch: 'SMIC advanced-node yield/capacity estimates · further BIS tightening',
    detail: 'The August 29, 2023 launch, confirmed by TechInsights teardown, showed SMIC producing 7nm-class logic without EUV; it reframed the debate on export-control effectiveness rather than changing near-term supply.',
    source: 'TechInsights teardown + Bloomberg reporting',
    timeline: [['Aug 29, 2023', 'Mate 60 Pro on sale'], ['Sep 2023', 'Teardown confirms SMIC N+2 die']] },

  { id: 'h2309_duv', dateISO: '2023-09-01', date: 'Sep 01, 2023', sev: 6, type: 'Export Control', conf: 'High',
    title: 'Dutch DUV licensing takes effect',
    summary: 'ASML\'s most capable immersion DUV systems (NXT:2000i and up) now need Dutch export licenses for China.',
    stages: ['litho'], countries: ['nl', 'cn'],
    first: 'Advanced immersion DUV shipments to China wind down; 2023 pull-forward buying peaks first.',
    second: 'By Jan 2024 U.S. pressure also halts some NXT:2050/2100 shipments; China DUV stockpile becomes its process ceiling.',
    watch: 'ASML China revenue share · license denials',
    detail: 'The Dutch rule published June 30, 2023 became effective September 1; ASML\'s China revenue spiked through late 2023 on pre-deadline deliveries, then advanced immersion sales were curtailed.',
    source: 'Dutch government gazette (official) + ASML investor disclosures',
    timeline: [['Jun 30, 2023', 'Rule published'], ['Sep 1, 2023', 'Licensing effective'], ['Jan 1, 2024', 'Further shipments halted']] },

  { id: 'h2310_bisupdate', dateISO: '2023-10-17', date: 'Oct 17, 2023', sev: 7, type: 'Export Control', conf: 'High',
    title: 'BIS performance-density rule closes A800/H800 path',
    summary: 'Updated AI-chip controls capture the China-market variants built to sit under the 2022 thresholds.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn'],
    first: 'NVIDIA A800/H800/L40S and similar parts now controlled; gray-zone SKU strategy ends.',
    second: 'Chinese cloud demand shifts to domestic accelerators (Ascend) and smuggled/loophole supply; H20-class compliant parts emerge.',
    watch: 'Compliant-SKU definitions · Chinese accelerator substitution',
    detail: 'The October 17, 2023 rules replaced the interconnect-speed test with performance-density thresholds and added a gray-zone notification band, capturing the A800/H800 designed after the 2022 rules.',
    source: 'BIS final rules 88 FR (official) + NVIDIA 8-K disclosures',
    timeline: [['Oct 17, 2023', 'Rules published, effective immediately for notified parts'], ['Nov 2023', 'NVIDIA designs H20-class compliant China SKUs']] },

  // ---------------- 2024 ----------------
  { id: 'h2401_noto', dateISO: '2024-01-01', date: 'Jan 01, 2024', sev: 4, type: 'Natural Disaster', conf: 'High',
    title: 'Noto Peninsula M7.6 earthquake',
    summary: 'New Year\'s Day quake forces inspections at Shin-Etsu and Toshiba sites; damage proves limited.',
    stages: ['wafers', 'mature_fab'], countries: ['jp'],
    first: 'Precautionary halts at wafer and device plants in Ishikawa/Niigata; restart within days-weeks.',
    second: 'Renews focus on Japan\'s materials concentration (wafers, resist) and seismic exposure.',
    watch: 'Shin-Etsu restart confirmations',
    detail: 'The January 1, 2024 M7.6 quake led to precautionary shutdowns and inspections (Shin-Etsu Naoetsu, Toshiba Kaga); most capacity restarted within two weeks with limited lasting supply impact.',
    source: 'Company statements + JMA seismic record',
    timeline: [['Jan 1, 2024', 'M7.6 quake'], ['Mid-Jan 2024', 'Most affected plants restarted']] },

  { id: 'h2404_hualien', dateISO: '2024-04-03', date: 'Apr 03, 2024', sev: 5, type: 'Natural Disaster', conf: 'High',
    title: 'Taiwan Hualien M7.4 earthquake',
    summary: 'Strongest Taiwan quake in 25 years halts fabs island-wide for inspection; recovery within days.',
    stages: ['adv_fab', 'memory_fab'], countries: ['tw'],
    first: 'TSMC evacuates and inspects; >70% tool recovery in 10 hours; some wafers scrapped.',
    second: 'Demonstrates seismic resilience engineering but reprices concentration risk for leading-edge capacity.',
    watch: 'Wafer-scrap estimates · quarterly guidance impact',
    detail: 'The April 3, 2024 M7.4 quake caused brief production halts at TSMC, UMC and Micron Taiwan; TSMC put the quarter\'s impact near NT$3B with no structural damage — a moderate, fast-recovered operational shock.',
    source: 'TSMC/UMC/Micron statements + earnings disclosures',
    timeline: [['Apr 3, 2024', 'Quake; fabs evacuate'], ['Apr 4–10, 2024', 'Staged recovery to full utilization']] },

  { id: 'h2405_huawei', dateISO: '2024-05-07', date: 'May 07, 2024', sev: 4, type: 'Export Control', conf: 'High',
    title: 'U.S. revokes Intel/Qualcomm licenses for Huawei',
    summary: 'Remaining licenses for laptop and handset chips to Huawei are withdrawn.',
    stages: ['design', 'logic_ai', 'm_consumer'], countries: ['us', 'cn'],
    first: 'Huawei PC/phone lines lose x86 and Snapdragon supply; revenue hit concentrated at Intel.',
    second: 'Completes Huawei\'s forced substitution onto Kirin/HiSilicon silicon across product lines.',
    watch: 'Huawei device teardowns · domestic substitution pace',
    detail: 'Commerce revoked the licenses on May 7, 2024, ending the last sanctioned U.S. chip flows into Huawei consumer devices; a targeted, modest-magnitude supply event with strategic substitution effects.',
    source: 'Commerce Department confirmation + company 8-K disclosures',
    timeline: [['May 7, 2024', 'License revocations confirmed']] },

  { id: 'h2412_bis3', dateISO: '2024-12-02', date: 'Dec 02, 2024', sev: 8, type: 'Export Control', conf: 'High',
    title: 'BIS third package: HBM controls + 140 entities',
    summary: 'HBM exports to China controlled for the first time; ~140 Chinese toolmakers and fabs added to the Entity List.',
    stages: ['hbm', 'memory_fab', 'depo', 'etch'], countries: ['us', 'cn', 'kr'],
    first: 'Samsung\'s China-bound HBM2E sales cut; Naura, AMEC, SiCarrier and peers listed; new FDPR extensions.',
    second: 'China responds next day with Ga/Ge/Sb export ban to the U.S. — first direct tit-for-tat material strike.',
    watch: 'HBM licensing practice · Chinese equipment-maker workarounds',
    detail: 'The December 2, 2024 package (nearly 700 pages) set an HBM performance-density control, added two new FDPRs and ~140 entities — the broadest single Entity List action in the sector to date.',
    source: 'BIS rules 89 FR (official) + CSIS/analyst summaries',
    timeline: [['Dec 2, 2024', 'Rules and entity additions published'], ['Dec 3, 2024', 'China retaliates with materials ban']] },

  { id: 'h2412_gaban', dateISO: '2024-12-03', date: 'Dec 03, 2024', sev: 7, type: 'Critical Material Risk', conf: 'High',
    title: 'China bans Ga/Ge/Sb exports to the U.S.',
    summary: 'Outright ban on gallium, germanium, antimony and superhard-material exports to the U.S.; stricter graphite review.',
    stages: ['gases', 'analog'], countries: ['cn', 'us'],
    first: 'Direct U.S. sourcing of these inputs ends; prices jump; rerouting through third countries begins.',
    second: 'First explicit country-targeted materials ban — escalation template later extended to rare earths.',
    watch: 'Third-country transshipment enforcement · U.S. domestic Ga/Ge projects',
    detail: 'Announced December 3, 2024 in direct response to the BIS package, the ban formalized what licensing had throttled since 2023 and extended dual-use export bans explicitly by destination country.',
    source: 'MOFCOM announcement (official) + Reuters',
    timeline: [['Dec 3, 2024', 'Ban announced, effective immediately']] },

  // ---------------- 2025 ----------------
  { id: 'h2501_diffusion', dateISO: '2025-01-13', date: 'Jan 13, 2025', sev: 6, type: 'Export Control', conf: 'Medium',
    title: 'AI Diffusion rule sets worldwide GPU tiers',
    summary: 'Outgoing administration publishes a three-tier global licensing framework for AI accelerators and model weights.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn'],
    first: 'Tier-2 country caps threaten sovereign-AI GPU deals; industry pushback is immediate.',
    second: 'Rescinded May 2025 before its compliance date — a policy-volatility, not supply, shock in the end.',
    watch: 'Compliance date · successor rules',
    detail: 'Published January 13, 2025 with a 120-day compliance window, the rule capped accelerator exports by country tier; it was rescinded May 13, 2025 before taking effect, but shaped deal-making all spring.',
    source: 'BIS interim final rule (official) + rescission notice',
    timeline: [['Jan 13, 2025', 'Rule published'], ['May 13, 2025', 'Rescinded before compliance date']] },

  { id: 'h2501_deepseek', dateISO: '2025-01-27', date: 'Jan 27, 2025', sev: 4, type: 'Technology Update', conf: 'High',
    title: 'DeepSeek R1 efficiency shock',
    summary: 'Chinese lab\'s frontier-class model trained on restricted-class hardware triggers a ~$600B NVIDIA selloff day.',
    stages: ['m_ai', 'logic_ai'], countries: ['cn', 'us'],
    first: 'Compute-demand assumptions repriced for a day; accelerator demand quickly reasserts.',
    second: 'Reframes export-control debate around training-efficiency workarounds; China AI stack credibility jumps.',
    watch: 'Frontier-lab compute disclosures · policy response',
    detail: 'The January 27, 2025 market reaction to DeepSeek R1 was the largest single-stock value drop on record; a demand-side sentiment event with winners and losers rather than a supply disruption.',
    source: 'Market data + DeepSeek technical report',
    timeline: [['Jan 20, 2025', 'R1 released'], ['Jan 27, 2025', 'Market shock day']] },

  { id: 'h2504_ree', dateISO: '2025-04-04', date: 'Apr 04, 2025', sev: 7, type: 'Critical Material Risk', conf: 'High',
    title: 'China controls seven heavy rare earths + magnets',
    summary: 'Licensing imposed on Dy, Tb, Y and four other heavy REEs plus sintered magnets, in tariff retaliation.',
    stages: ['gases', 'analog', 'm_auto'], countries: ['cn', 'us', 'jp', 'de'],
    first: 'Magnet shipments pause ~2 months; auto and defense supply chains scramble.',
    second: 'Ford and European plants see stoppages by June; REE leverage becomes the center of trade talks.',
    watch: 'License throughput · non-China magnet capacity',
    detail: 'The April 4, 2025 controls (still active as of mid-2026) halted heavy-REE magnet exports until licensing spun up; automakers reported line stoppages within two months, and the controls anchored every subsequent truce negotiation.',
    source: 'MOFCOM announcement (official) + automaker disclosures',
    timeline: [['Apr 4, 2025', 'Controls announced'], ['Jun 2025', 'Auto plant stoppages reported'], ['May 2026', 'Still fully active per trade-press review']] },

  { id: 'h2504_h20', dateISO: '2025-04-09', date: 'Apr 09, 2025', sev: 7, type: 'Export Control', conf: 'High',
    title: 'H20/MI308 China sales require licenses',
    summary: 'The compliant-SKU path closes: NVIDIA H20 and AMD MI308 now need export licenses; NVIDIA takes a $5.5B charge.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn'],
    first: 'China accelerator revenue halts for a quarter; inventory written down.',
    second: 'Chinese cloud buyers shift to Ascend and stockpiles; sets up the July 2025 licensing reversal.',
    watch: 'License grants · Chinese substitute capacity',
    detail: 'On April 9, 2025 the administration informed NVIDIA that H20 exports to China required licenses (effective indefinitely); NVIDIA disclosed a $5.5B charge on April 15, with AMD taking a parallel hit on MI308.',
    source: 'NVIDIA/AMD 8-K filings + Commerce statements',
    timeline: [['Apr 9, 2025', 'License requirement communicated'], ['Apr 15, 2025', 'NVIDIA $5.5B charge disclosed']] },

  { id: 'h2505_rescind', dateISO: '2025-05-13', date: 'May 13, 2025', sev: 4, type: 'Export Control', conf: 'Medium',
    title: 'AI Diffusion rule rescinded',
    summary: 'BIS withdraws the tiered global framework before its compliance date; issues chip-smuggling and Huawei-Ascend guidance instead.',
    stages: ['logic_ai', 'm_ai'], countries: ['us'],
    first: 'Tier-2 GPU caps vanish; Gulf sovereign-AI deals proceed.',
    second: 'Policy volatility itself becomes the planning risk; bilateral deal-by-deal controls replace the framework.',
    watch: 'Successor rule drafts · Gulf deal licensing',
    detail: 'The May 13, 2025 rescission (effective before the rule\'s May 15 compliance date) reversed the tier system while keeping Huawei Ascend usage warnings — a mitigating policy reversal for non-China markets.',
    source: 'BIS rescission notice (official)',
    timeline: [['May 13, 2025', 'Rescission announced']] },

  { id: 'h2507_h20back', dateISO: '2025-07-15', date: 'Jul 15, 2025', sev: 5, type: 'Export Control', conf: 'Medium',
    title: 'H20 China sales resume under license deal',
    summary: 'Washington signals license approvals for H20 exports to China; a revenue-share arrangement follows in August.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn'],
    first: 'China accelerator flows partially restore; NVIDIA/AMD resume compliant-SKU sales.',
    second: 'Beijing counter-pressures buyers toward domestic chips; the arrangement stays politically fragile into 2026.',
    watch: 'License volumes · Chinese procurement guidance',
    detail: 'In mid-July 2025 the administration indicated H20 licenses would be granted (formalized with a 15% China-revenue-share arrangement in August); flows resumed well below pre-April run-rates amid Chinese state pressure to buy domestic.',
    source: 'Company statements + Commerce confirmations',
    timeline: [['Jul 15, 2025', 'License approvals signaled'], ['Aug 2025', 'Revenue-share arrangement reported']] },

  { id: 'h2509_nexperia', dateISO: '2025-09-30', date: 'Sep 30, 2025', sev: 7, type: 'Geopolitical Risk', conf: 'High',
    title: 'Nexperia seizure triggers auto-chip crisis',
    summary: 'Dutch state takes control of Chinese-owned Nexperia; China blocks its China-assembled output, starving auto lines of basic chips.',
    stages: ['analog', 'mature_fab', 'osat', 'm_auto'], countries: ['nl', 'cn', 'de', 'jp'],
    first: 'Legacy discretes/logic supply to automakers breaks; Honda alone cuts ~110k vehicles (~$1B) in North America.',
    second: 'Shows a single mid-tier supplier chokepoint can idle global auto lines; carmakers build direct wafer-shipping workarounds.',
    watch: 'Dutch-Chinese negotiations · Nexperia China wafer sourcing · Enterprise Chamber rulings',
    detail: 'The Netherlands invoked the Goods Availability Act on September 30, 2025; China retaliated by banning exports from Nexperia\'s Chinese assembly sites, freezing ~70% of its packaged output. Partial Chinese exemptions from November eased the squeeze; the governance dispute continued into 2026 with the Enterprise Chamber upholding interim measures on February 11, 2026.',
    source: 'Dutch ministry statements (official) + CNBC/Reuters + Honda disclosures',
    timeline: [['Sep 30, 2025', 'Dutch state asserts control'], ['Oct 4, 2025', 'China export ban on Nexperia China output'], ['Nov 2025', 'Auto production cuts peak; partial exemptions granted'], ['Feb 11, 2026', 'Enterprise Chamber upholds measures, orders investigation']] },

  { id: 'h2510_reemax', dateISO: '2025-10-09', date: 'Oct 09, 2025', sev: 8, type: 'Critical Material Risk', conf: 'High',
    title: 'China\'s sweeping rare-earth control expansion',
    summary: 'Five more REEs, refining/magnet technology, and a 0.1% de-minimis extraterritorial license rule on foreign-made goods.',
    stages: ['gases', 'analog', 'm_auto', 'm_ai'], countries: ['cn', 'us', 'jp', 'de', 'kr'],
    first: 'Any product worldwide containing >0.1% Chinese-origin REE content faces Chinese licensing — unprecedented extraterritorial reach.',
    second: 'Forces the October 30 Busan truce; controls suspended for one year rather than removed, keeping leverage loaded.',
    watch: 'Truce expiry Nov 10, 2026 · non-China separation capacity',
    detail: 'Announced October 9, 2025 ahead of the APEC summit, the package extended controls to holmium, erbium, thulium, europium, ytterbium plus processing technology, with FDPR-style extraterritorial licensing; it was suspended (not repealed) under the truce weeks later.',
    source: 'MOFCOM announcements (official) + Clark Hill / mining-press analysis',
    timeline: [['Oct 9, 2025', 'Expansion announced'], ['Oct 30, 2025', 'Busan summit truce'], ['Nov 7, 2025', 'One-year suspension formalized']] },

  { id: 'h2510_truce', dateISO: '2025-10-30', date: 'Oct 30, 2025', sev: 5, type: 'Policy Signal', conf: 'High',
    title: 'Busan truce pauses the materials war',
    summary: 'U.S.-China summit yields a one-year suspension of the October REE expansion and tariff de-escalation.',
    stages: ['gases', 'analog'], countries: ['us', 'cn'],
    first: 'October-package licensing paused through Nov 10, 2026; April 2025 heavy-REE controls stay active.',
    second: 'Supply planning gets a 12-month window, not a resolution — leverage remains staged for re-activation.',
    watch: 'Suspension expiry · blacklist actions eroding the truce',
    detail: 'The October 30, 2025 Busan meeting produced a formalized (November 7) one-year suspension of the sweeping October controls; the April 2025 regime remained fully active, and June 2026 blacklistings of U.S. REE firms strained the truce.',
    source: 'Joint readouts + Bloomberg (Nov 7, 2025 formalization)',
    timeline: [['Oct 30, 2025', 'Summit agreement'], ['Nov 7, 2025', 'Suspension formalized'], ['Nov 10, 2026', 'Suspension expires unless extended']] },

  { id: 'h2512_memory', dateISO: '2025-12-10', date: 'Dec 10, 2025', sev: 6, type: 'Market Shock', conf: 'High',
    title: 'Memory shortage ignites as HBM eats DRAM capacity',
    summary: 'Samsung/SK Hynix/Micron capacity reallocation to HBM leaves conventional DRAM/NAND critically short; contract prices surge.',
    stages: ['memory_fab', 'hbm', 'm_consumer'], countries: ['kr', 'us', 'tw'],
    first: 'Consumer DRAM/NAND allocations cut; SSD/DRAM street prices roughly double from late-2025 levels.',
    second: 'Smartphone/PC BOM costs jump into 2026; IDC calls it a "tsunami-like shock" originating in memory.',
    watch: 'Contract price fixings · HBM wafer share · smartphone build plans',
    detail: 'By December 2025 the big-three memory makers had shifted wafer starts decisively toward HBM (SK Hynix\'s 2026 HBM output sold out in October); conventional DRAM supply growth fell far below demand, starting the steepest memory price cycle in a decade.',
    source: 'IDC memory-crisis analysis + TrendForce contract data',
    timeline: [['Oct 2025', 'SK Hynix 2026 HBM sold out'], ['Dec 2025', 'Contract price surges broaden'], ['Q1 2026', 'Shortage peaks (see follow-on event)']] },

  { id: 'h2512_yilan', dateISO: '2025-12-27', date: 'Dec 27, 2025', sev: 3, type: 'Natural Disaster', conf: 'High',
    title: 'M7.0 Yilan quake — fabs ride it out',
    summary: 'Strongest Taiwan quake in 27 years; TSMC facilities escape unharmed, validating seismic hardening.',
    stages: ['adv_fab', 'memory_fab'], countries: ['tw'],
    first: 'Brief precautionary checks; no material wafer loss reported.',
    second: 'Contrast with Jan/Apr 2024-25 events shows isolation investment paying off; concentration hazard unchanged.',
    watch: 'Aftershock activity · insurer repricing',
    detail: 'The December 27, 2025 offshore Yilan M7.0 event rattled northern Taiwan but produced no significant fab damage — a hazard signal on Taiwan concentration rather than a realized supply shock.',
    source: 'TSMC statement + Tom\'s Hardware / DigiTimes coverage',
    timeline: [['Dec 27, 2025', 'Quake strikes offshore Yilan'], ['Dec 29, 2025', 'Fabs confirm normal operations']] },

  // ---------------- 2026 ----------------
  { id: 'h2601_ease', dateISO: '2026-01-15', date: 'Jan 15, 2026', sev: 5, type: 'Export Control', conf: 'High',
    title: 'BIS moves H200-class exports to case-by-case review',
    summary: 'Final rule effective Jan 15–16, 2026 relaxes presumption of denial for NVIDIA H200 / AMD MI325X China licenses.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn'],
    first: 'A licensed channel for near-frontier accelerators into China reopens.',
    second: 'Congress pushes back (AI OVERWATCH Act, MATCH Act) — executive easing vs. legislative tightening defines 2026.',
    watch: 'License grant volume · congressional veto legislation',
    detail: 'The BIS final rule effective January 15, 2026 shifted H200/MI325X-class China exports from presumptive denial to case-by-case review — the clearest easing step since the H20 arrangement, immediately contested in Congress.',
    source: 'BIS final rule (official) + Congress.gov CRS R48642',
    timeline: [['Jan 15, 2026', 'Rule effective'], ['Jan 22, 2026', 'AI OVERWATCH Act advances in committee']] },

  { id: 'h2603_memorypeak', dateISO: '2026-03-10', date: 'Mar 10, 2026', sev: 7, type: 'Market Shock', conf: 'High',
    title: 'Memory price shock peaks: DRAM +90–95% QoQ',
    summary: 'Q1 2026 conventional DRAM contracts nearly double; NAND follows with +70–75% in Q2 — worst squeeze of the cycle.',
    stages: ['memory_fab', 'm_consumer', 'm_ai'], countries: ['kr', 'us', 'tw'],
    first: 'Smartphone/PC makers cut builds or eat BOM inflation; server RAM prices roughly double.',
    second: 'Supply growth (~16% DRAM / 17% NAND) stays under demand; relief not expected before 2027 fab additions.',
    watch: 'Q3 contract fixings · Micron/SK Hynix new-fab timelines · demand destruction signs',
    detail: 'Q1 2026 DRAM contract prices rose 90–95% QoQ — beyond worst-case January forecasts — with NAND up 70–75% in Q2; analysts expect elevated pricing through 2027 as HBM takes ~25% of DRAM wafer output.',
    source: 'TrendForce/IDC contract data + NAND Research crisis updates',
    timeline: [['Mar 2026', 'Q1 fixings confirm ~2x DRAM'], ['May 2026', 'NAND +70–75% QoQ fixings'], ['Q3 2026', 'Price momentum begins cooling at consumer affordability limits']] },

  { id: 'h2604_match', dateISO: '2026-04-02', date: 'Apr 02, 2026', sev: 4, type: 'Policy Signal', conf: 'Medium',
    title: 'MATCH Act introduced in Congress',
    summary: 'Bill would ban DUV tool sales to all of China, designate SMIC/CXMT/YMTC/Hua Hong/Huawei, and force allied alignment.',
    stages: ['litho', 'mature_fab'], countries: ['us', 'cn', 'nl', 'jp'],
    first: 'No immediate supply effect — a legislative escalation marker against executive easing.',
    second: 'If enacted, would extend U.S. jurisdiction over allied tooling exports — the sharpest proposed expansion since Oct 2022.',
    watch: 'Committee progress · allied government reactions',
    detail: 'Introduced April 2, 2026 by Reps. Baumgartner and Moolenaar, the MATCH Act targets legacy-node tooling for the first time (DUV ban to all Chinese facilities) with an allied-matching mechanism; passage remains uncertain.',
    source: 'Bill text via Congress.gov + Semiconductors Insight analysis',
    timeline: [['Apr 2, 2026', 'Introduced'], ['H2 2026', 'Committee consideration expected']] },

  { id: 'h2606_subs', dateISO: '2026-06-01', date: 'Jun 01, 2026', sev: 6, type: 'Export Control', conf: 'High',
    title: 'AI-chip ban extended to Chinese firms\' overseas units',
    summary: 'Commerce affirms licensing applies to any buyer headquartered in or parented from China, wherever located.',
    stages: ['logic_ai', 'm_ai'], countries: ['us', 'cn', 'sg', 'my'],
    first: 'Closes the offshore-subsidiary channel (Singapore/Malaysia data-center builds by Chinese firms).',
    second: 'Chinese cloud operators\' overseas expansion loses U.S. accelerator access; substitution pressure rises again.',
    watch: 'Enforcement actions · Southeast Asia data-center procurement',
    detail: 'The June 1, 2026 clarification states license requirements follow Chinese ownership rather than shipment geography — targeting rerouted accelerator deployments through third-country subsidiaries.',
    source: 'Commerce notice + Al Jazeera (Jun 1, 2026)',
    timeline: [['Jun 1, 2026', 'Clarification issued']] },

  { id: 'h2606_mpban', dateISO: '2026-06-22', date: 'Jun 22, 2026', sev: 5, type: 'Critical Material Risk', conf: 'High',
    title: 'China blacklists U.S. rare-earth champions',
    summary: 'MP Materials and USA Rare Earth added to China\'s export-control list, straining the Busan truce.',
    stages: ['gases', 'm_auto'], countries: ['cn', 'us'],
    first: 'Chinese inputs/equipment cut off from the flagship U.S. REE build-out.',
    second: 'Signals the truce may not survive its Nov 10, 2026 expiry; supply chains re-hedge.',
    watch: 'Truce extension talks · U.S. separation-capacity milestones',
    detail: 'Five weeks after the May 2026 Trump–Xi Beijing summit, Beijing blacklisted the two leading U.S. rare-earth producers on June 22, 2026 — ending the post-summit détente signal and targeting the U.S. supply-chain comeback directly.',
    source: 'MOFCOM listing + FDD analysis (Jun 24, 2026)',
    timeline: [['May 2026', 'Beijing summit raises truce-extension hopes'], ['Jun 22, 2026', 'MP Materials / USA Rare Earth blacklisted']] },
];
