/* ====================================================================
   SSCIM seed dataset — real-data pass (mid-2026).
   Baseline values are the original curated-sample dataset; entries below
   carry corrections drawn from four research passes (foundry/fab/packaging,
   equipment/materials, memory/EDA/design, analog/systems/end-market),
   each grounded in company filings (10-K/20-F), TrendForce/TechInsights/
   Gartner market-share tracking, and named trade press — see DATA_NOTES
   at the bottom for the citation behind each flagged correction.

   Every number here is still a *model input*, not a live feed: tiers per
   README §8 are B (institutional/analyst report), C (official filing), or
   D (analyst judgment / no citable public figure exists). Fields without
   an explicit note in DATA_NOTES are carried over from the original
   illustrative sample and should be read as Tier D until Phase-1 sourcing
   replaces them individually.
   ==================================================================== */

export const COUNTRY_NAMES = {
  us: "United States", cn: "China", tw: "Taiwan", kr: "South Korea", jp: "Japan",
  nl: "Netherlands", de: "Germany", fr: "France", uk: "United Kingdom", be: "Belgium",
  ie: "Ireland", il: "Israel", sg: "Singapore", my: "Malaysia", vn: "Vietnam", ph: "Philippines",
};
export const COUNTRY_POS = {
  us: [39, -98], cn: [35, 104], tw: [23.7, 121], kr: [36.5, 127.8], jp: [36.2, 138.2],
  nl: [52.5, 5.3], de: [50.5, 10.4], fr: [46.5, 2.5], uk: [54.5, -2], be: [50.6, 4.5],
  ie: [53.2, -8], il: [31.5, 35], sg: [1.35, 103.8], my: [4.2, 102], vn: [16, 106], ph: [13, 122],
};

export const STAGES = [
  { id: "research", name: "Research / IP", x: 70, y: 45, value: 20, subst: 6.5, market: 3.0,
    shares: { us: 0.3, uk: 0.2, be: 0.15, de: 0.1, jp: 0.1, cn: 0.1, fr: 0.05 } },
  { id: "eda", name: "EDA software", x: 70, y: 115, value: 15, subst: 9.0, market: 5.0,
    shares: { us: 0.63, de: 0.13, cn: 0.06, jp: 0.02 } },
  { id: "design", name: "Chip design", x: 70, y: 185, value: 250, subst: 6.0, market: 9.0,
    shares: { us: 0.5, tw: 0.15, cn: 0.15, kr: 0.07, jp: 0.05, il: 0.05, uk: 0.03 } },
  { id: "wafers", name: "Silicon wafers", x: 70, y: 255, value: 15, subst: 7.5, market: 4.0,
    shares: { jp: 0.55, tw: 0.15, kr: 0.1, de: 0.1, cn: 0.06 } },
  { id: "resist", name: "Photoresists", x: 70, y: 325, value: 3, subst: 8.5, market: 3.5,
    shares: { jp: 0.76, us: 0.1, kr: 0.05, cn: 0.05 } },
  { id: "gases", name: "Specialty gases / chem", x: 70, y: 395, value: 8, subst: 7.0, market: 3.5,
    shares: { jp: 0.22, de: 0.22, fr: 0.18, us: 0.18, cn: 0.1, kr: 0.1 } },
  { id: "substrates", name: "IC substrates (ABF)", x: 70, y: 465, value: 12, subst: 7.5, market: 4.5,
    shares: { jp: 0.38, tw: 0.32, kr: 0.14, de: 0.08, cn: 0.08 } },
  { id: "litho", name: "Lithography (EUV/DUV)", x: 300, y: 85, value: 30, subst: 9.8, market: 7.0,
    shares: { nl: 0.9, jp: 0.09 } },
  { id: "depo", name: "Deposition", x: 300, y: 175, value: 20, subst: 7.5, market: 6.0,
    shares: { us: 0.4, jp: 0.28, nl: 0.12, kr: 0.06, cn: 0.14 } },
  { id: "etch", name: "Etch & clean", x: 300, y: 265, value: 22, subst: 7.5, market: 6.0,
    shares: { us: 0.48, jp: 0.28, cn: 0.14, kr: 0.05 } },
  { id: "cmp", name: "CMP & slurries", x: 300, y: 355, value: 6, subst: 6.5, market: 4.0,
    shares: { us: 0.55, jp: 0.35, kr: 0.05, fr: 0.05 } },
  { id: "metro", name: "Metrology / inspection", x: 300, y: 445, value: 13, subst: 8.0, market: 5.5,
    shares: { us: 0.68, jp: 0.12, nl: 0.08, il: 0.06, de: 0.06 } },
  { id: "adv_fab", name: "Advanced fab (≤7nm)", x: 520, y: 130, value: 120, subst: 9.5, market: 8.5,
    shares: { tw: 0.62, kr: 0.2, us: 0.12, jp: 0.04, ie: 0.02 } },
  { id: "mature_fab", name: "Mature-node fab", x: 520, y: 265, value: 90, subst: 5.0, market: 6.0,
    shares: { cn: 0.3, tw: 0.28, us: 0.1, jp: 0.1, de: 0.07, kr: 0.06, sg: 0.04, il: 0.03, fr: 0.02 } },
  { id: "memory_fab", name: "Memory fab (DRAM/NAND)", x: 520, y: 400, value: 130, subst: 6.5, market: 8.5,
    shares: { kr: 0.6, us: 0.18, jp: 0.09, cn: 0.07, sg: 0.02, tw: 0.04 } },
  { id: "logic_ai", name: "Logic & AI accelerators", x: 690, y: 90, value: 300, subst: 6.5, market: 9.5,
    shares: { us: 0.68, tw: 0.13, cn: 0.09, kr: 0.1 } },
  { id: "analog", name: "Analog / power / RF", x: 690, y: 265, value: 90, subst: 5.0, market: 6.0,
    shares: { us: 0.38, jp: 0.17, de: 0.15, cn: 0.13, fr: 0.07, il: 0.005 } },
  { id: "hbm", name: "HBM", x: 690, y: 415, value: 25, subst: 8.5, market: 9.0,
    shares: { kr: 0.74, us: 0.26 } },
  { id: "adv_pkg", name: "Advanced packaging", x: 860, y: 170, value: 45, subst: 8.0, market: 7.5,
    shares: { tw: 0.5, us: 0.15, kr: 0.15, cn: 0.1, my: 0.05, sg: 0.05 } },
  { id: "osat", name: "OSAT / test", x: 860, y: 350, value: 40, subst: 4.5, market: 5.0,
    shares: { tw: 0.4, cn: 0.26, my: 0.13, us: 0.07, sg: 0.06, ph: 0.04, vn: 0.04 } },
  { id: "systems", name: "Final systems (ODM/EMS)", x: 1000, y: 260, value: 500, subst: 3.5, market: 6.5,
    shares: { cn: 0.4, tw: 0.18, us: 0.12, my: 0.1, vn: 0.1, de: 0.05, sg: 0.05 } },
  { id: "m_ai", name: "AI data centers", x: 1140, y: 110, value: 350, subst: 3.0, market: 9.0,
    shares: { us: 0.62, cn: 0.13, de: 0.1, jp: 0.1, sg: 0.05 } },
  { id: "m_auto", name: "Automotive / industrial", x: 1140, y: 260, value: 90, subst: 3.5, market: 6.0,
    shares: { cn: 0.3, jp: 0.2, us: 0.22, de: 0.13, kr: 0.1, fr: 0.05 } },
  { id: "m_consumer", name: "Consumer / mobile", x: 1140, y: 410, value: 250, subst: 3.0, market: 6.5,
    shares: { cn: 0.4, us: 0.25, kr: 0.2, jp: 0.1, vn: 0.05 } },
];

export const FLOW_EDGES = [
  ["research", "eda"], ["research", "design"], ["eda", "design"],
  ["design", "adv_fab"], ["design", "mature_fab"],
  ["wafers", "adv_fab"], ["wafers", "mature_fab"], ["wafers", "memory_fab"],
  ["resist", "litho"], ["gases", "depo"], ["gases", "etch"], ["substrates", "adv_pkg"],
  ["litho", "adv_fab"], ["litho", "mature_fab"], ["litho", "memory_fab"],
  ["depo", "adv_fab"], ["depo", "memory_fab"],
  ["etch", "adv_fab"], ["etch", "mature_fab"],
  ["cmp", "adv_fab"], ["metro", "adv_fab"], ["metro", "memory_fab"],
  ["adv_fab", "logic_ai"], ["mature_fab", "analog"], ["memory_fab", "hbm"], ["memory_fab", "osat"],
  ["logic_ai", "adv_pkg"], ["hbm", "adv_pkg"], ["analog", "osat"],
  ["adv_pkg", "systems"], ["osat", "systems"],
  ["systems", "m_ai"], ["systems", "m_auto"], ["systems", "m_consumer"],
];

export const TIER_LABELS = [["INPUTS & IP", 70], ["EQUIPMENT", 300], ["FABRICATION", 520], ["CHIP PRODUCTS", 690], ["BACKEND", 860], ["SYSTEMS", 1000], ["END MARKETS", 1140]];

export const COMPANIES = [
  { id: "arm", name: "Arm", country: "uk", stakes: { research: 0.35 } },
  { id: "imec", name: "imec", country: "be", stakes: { research: 0.2 } },
  { id: "synopsys", name: "Synopsys", country: "us", stakes: { eda: 0.34 } },
  { id: "cadence", name: "Cadence", country: "us", stakes: { eda: 0.3 } },
  { id: "siemens_eda", name: "Siemens EDA", country: "de", stakes: { eda: 0.13 } },
  { id: "nvidia", name: "NVIDIA", country: "us", stakes: { design: 0.22, logic_ai: 0.78 } },
  { id: "amd", name: "AMD", country: "us", stakes: { design: 0.1, logic_ai: 0.07 } },
  { id: "qualcomm", name: "Qualcomm", country: "us", stakes: { design: 0.12 } },
  { id: "apple", name: "Apple (silicon)", country: "us", stakes: { design: 0.1, m_consumer: 0.26 } },
  { id: "mediatek", name: "MediaTek", country: "tw", stakes: { design: 0.1 } },
  { id: "hisilicon", name: "HiSilicon (Huawei)", country: "cn", stakes: { design: 0.06, logic_ai: 0.05 } },
  { id: "shinetsu", name: "Shin-Etsu", country: "jp", stakes: { wafers: 0.29, resist: 0.18 } },
  { id: "sumco", name: "SUMCO", country: "jp", stakes: { wafers: 0.24 } },
  { id: "globalwafers", name: "GlobalWafers", country: "tw", stakes: { wafers: 0.155 } },
  { id: "jsr", name: "JSR", country: "jp", stakes: { resist: 0.24 } },
  { id: "tok", name: "TOK", country: "jp", stakes: { resist: 0.2 } },
  { id: "linde", name: "Linde", country: "de", stakes: { gases: 0.2 } },
  { id: "airliquide", name: "Air Liquide", country: "fr", stakes: { gases: 0.18 } },
  { id: "ibiden", name: "Ibiden", country: "jp", stakes: { substrates: 0.17 } },
  { id: "unimicron", name: "Unimicron", country: "tw", stakes: { substrates: 0.18 } },
  { id: "asml", name: "ASML", country: "nl", stakes: { litho: 0.9, metro: 0.1 } },
  { id: "nikon", name: "Nikon", country: "jp", stakes: { litho: 0.045 } },
  { id: "canon", name: "Canon", country: "jp", stakes: { litho: 0.055 } },
  { id: "amat", name: "Applied Materials", country: "us", stakes: { depo: 0.3, etch: 0.3, cmp: 0.4, metro: 0.09 } },
  { id: "tel", name: "Tokyo Electron", country: "jp", stakes: { depo: 0.15, etch: 0.15 } },
  { id: "lam", name: "Lam Research", country: "us", stakes: { depo: 0.15, etch: 0.32 } },
  { id: "kla", name: "KLA", country: "us", stakes: { metro: 0.58 } },
  { id: "tsmc", name: "TSMC", country: "tw", stakes: { adv_fab: 0.85, mature_fab: 0.2, adv_pkg: 0.35 } },
  { id: "samsung", name: "Samsung", country: "kr", stakes: { adv_fab: 0.07, memory_fab: 0.35, hbm: 0.21, m_consumer: 0.2 } },
  { id: "intel", name: "Intel", country: "us", stakes: { adv_fab: 0.025, adv_pkg: 0.08 } },
  { id: "rapidus", name: "Rapidus", country: "jp", stakes: { adv_fab: 0.008 } },
  { id: "smic", name: "SMIC", country: "cn", stakes: { mature_fab: 0.11 } },
  { id: "umc", name: "UMC", country: "tw", stakes: { mature_fab: 0.11 } },
  { id: "gf", name: "GlobalFoundries", country: "us", stakes: { mature_fab: 0.07 } },
  { id: "ti", name: "Texas Instruments", country: "us", stakes: { mature_fab: 0.05, analog: 0.19 } },
  { id: "infineon", name: "Infineon", country: "de", stakes: { analog: 0.065 } },
  { id: "st", name: "STMicro", country: "fr", stakes: { analog: 0.045, mature_fab: 0.03 } },
  { id: "tower", name: "Tower Semi", country: "il", stakes: { mature_fab: 0.02 } },
  { id: "skhynix", name: "SK hynix", country: "kr", stakes: { memory_fab: 0.253, hbm: 0.53 } },
  { id: "micron", name: "Micron", country: "us", stakes: { memory_fab: 0.19, hbm: 0.24 } },
  { id: "ymtc", name: "YMTC", country: "cn", stakes: { memory_fab: 0.044 } },
  { id: "cxmt", name: "CXMT", country: "cn", stakes: { memory_fab: 0.053 } },
  { id: "kioxia", name: "Kioxia", country: "jp", stakes: { memory_fab: 0.047 } },
  { id: "ase", name: "ASE", country: "tw", stakes: { adv_pkg: 0.12, osat: 0.4 } },
  { id: "amkor", name: "Amkor", country: "us", stakes: { osat: 0.14, adv_pkg: 0.08 } },
  { id: "jcet", name: "JCET", country: "cn", stakes: { osat: 0.11 } },
  { id: "foxconn", name: "Foxconn", country: "tw", stakes: { systems: 0.4 } },
  /* ---- expansion to 107+ companies ---- */
  { id: "ibm_res", name: "IBM Research", country: "us", stakes: { research: 0.1 } },
  { id: "leti", name: "CEA-Leti", country: "fr", stakes: { research: 0.08 } },
  { id: "ansys", name: "Ansys", country: "us", stakes: {} },
  { id: "empyrean", name: "Empyrean", country: "cn", stakes: { eda: 0.015 } },
  { id: "broadcom", name: "Broadcom", country: "us", stakes: { design: 0.12, logic_ai: 0.03 } },
  { id: "marvell", name: "Marvell", country: "us", stakes: { design: 0.05, logic_ai: 0.01 } },
  { id: "unisoc", name: "UNISOC", country: "cn", stakes: { design: 0.04 } },
  { id: "sksiltron", name: "SK Siltron", country: "kr", stakes: { wafers: 0.095 } },
  { id: "siltronic", name: "Siltronic", country: "de", stakes: { wafers: 0.085 } },
  { id: "nsig", name: "NSIG", country: "cn", stakes: { wafers: 0.025 } },
  { id: "sumitomo_chem", name: "Sumitomo Chemical", country: "jp", stakes: { resist: 0.08 } },
  { id: "dupont", name: "DuPont", country: "us", stakes: { resist: 0.07 } },
  { id: "resonac", name: "Resonac", country: "jp", stakes: { gases: 0.12 } },
  { id: "tnsc", name: "Taiyo Nippon Sanso", country: "jp", stakes: { gases: 0.13 } },
  { id: "airproducts", name: "Air Products", country: "us", stakes: { gases: 0.1 } },
  { id: "skmaterials", name: "SK Materials", country: "kr", stakes: { gases: 0.08 } },
  { id: "shinko", name: "Shinko Electric", country: "jp", stakes: { substrates: 0.13 } },
  { id: "samsungem", name: "Samsung Electro-Mech", country: "kr", stakes: { substrates: 0.12 } },
  { id: "ats", name: "AT&S", country: "de", stakes: { substrates: 0.13 } },
  { id: "asmi", name: "ASM International", country: "nl", stakes: { depo: 0.12 } },
  { id: "kokusai", name: "Kokusai Electric", country: "jp", stakes: { depo: 0.08 } },
  { id: "naura", name: "NAURA", country: "cn", stakes: { depo: 0.1, etch: 0.08 } },
  { id: "amec", name: "AMEC", country: "cn", stakes: { etch: 0.07 } },
  { id: "hitachiht", name: "Hitachi High-Tech", country: "jp", stakes: { metro: 0.06, etch: 0.05 } },
  { id: "ebara", name: "Ebara", country: "jp", stakes: { cmp: 0.3 } },
  { id: "entegris", name: "Entegris", country: "us", stakes: { cmp: 0.12 } },
  { id: "onto", name: "Onto Innovation", country: "us", stakes: { metro: 0.08 } },
  { id: "nova", name: "Nova", country: "il", stakes: { metro: 0.06 } },
  { id: "huahong", name: "Hua Hong", country: "cn", stakes: { mature_fab: 0.05 } },
  { id: "vis", name: "Vanguard (VIS)", country: "tw", stakes: { mature_fab: 0.025 } },
  { id: "nexchip", name: "Nexchip", country: "cn", stakes: { mature_fab: 0.03 } },
  { id: "sonysemi", name: "Sony Semiconductor", country: "jp", stakes: { mature_fab: 0.05 } },
  { id: "renesas", name: "Renesas", country: "jp", stakes: { analog: 0.025, mature_fab: 0.04 } },
  { id: "bosch", name: "Bosch", country: "de", stakes: { mature_fab: 0.03, m_auto: 0.1 } },
  { id: "nanya", name: "Nanya", country: "tw", stakes: { memory_fab: 0.013 } },
  { id: "winbond", name: "Winbond", country: "tw", stakes: { memory_fab: 0.005 } },
  { id: "google", name: "Google (TPU/Cloud)", country: "us", stakes: { logic_ai: 0.06, m_ai: 0.17 } },
  { id: "amazon", name: "Amazon (AWS)", country: "us", stakes: { logic_ai: 0.04, m_ai: 0.18 } },
  { id: "cambricon", name: "Cambricon", country: "cn", stakes: { logic_ai: 0.008 } },
  { id: "biren", name: "Biren", country: "cn", stakes: { logic_ai: 0.003 } },
  { id: "onsemi", name: "onsemi", country: "us", stakes: { analog: 0.035 } },
  { id: "adi", name: "Analog Devices", country: "us", stakes: { analog: 0.135 } },
  { id: "nxp", name: "NXP", country: "nl", stakes: { analog: 0.035 } },
  { id: "microchip", name: "Microchip", country: "us", stakes: { analog: 0.03 } },
  { id: "spil", name: "SPIL", country: "tw", stakes: { adv_pkg: 0.08 } },
  { id: "pti", name: "Powertech (PTI)", country: "tw", stakes: { adv_pkg: 0.06 } },
  { id: "utac", name: "UTAC", country: "sg", stakes: { osat: 0.015 } },
  { id: "kyec", name: "KYEC", country: "tw", stakes: { osat: 0.02 } },
  { id: "inari", name: "Inari Amertron", country: "my", stakes: { osat: 0.015 } },
  { id: "quanta", name: "Quanta", country: "tw", stakes: { systems: 0.2 } },
  { id: "wistron", name: "Wistron", country: "tw", stakes: { systems: 0.09 } },
  { id: "supermicro", name: "Supermicro", country: "us", stakes: { systems: 0.04 } },
  { id: "luxshare", name: "Luxshare", country: "cn", stakes: { systems: 0.05 } },
  { id: "microsoft", name: "Microsoft (Azure)", country: "us", stakes: { m_ai: 0.1 } },
  { id: "meta", name: "Meta", country: "us", stakes: { m_ai: 0.12 } },
  { id: "alibaba", name: "Alibaba Cloud", country: "cn", stakes: { m_ai: 0.03 } },
  { id: "tesla", name: "Tesla", country: "us", stakes: { m_auto: 0.04 } },
  { id: "denso", name: "Toyota / Denso", country: "jp", stakes: { m_auto: 0.13 } },
  { id: "vw", name: "VW Group", country: "de", stakes: { m_auto: 0.1 } },
  { id: "xiaomi", name: "Xiaomi", country: "cn", stakes: { m_consumer: 0.1 } },
  { id: "lenovo", name: "Lenovo", country: "cn", stakes: { m_consumer: 0.1 } },
  { id: "hp", name: "HP", country: "us", stakes: { m_consumer: 0.07 } },
];
export const COMPANY_BY_ID = Object.fromEntries(COMPANIES.map((c) => [c.id, c]));

export const COMP_META = {
  choke: ["Chokepoint centrality", "GRAPH"], geo: ["Geographic concentration", "HHI"],
  policy: ["Policy exposure", "POLICY DB"], subst: ["Substitutability risk", "ANALYST"],
  shock: ["Event shock severity", "EVENT ENGINE"], market: ["Market sensitivity", "ANALYST"],
};

export const DOMAINS = {
  arm: "arm.com", imec: "imec-int.com", synopsys: "synopsys.com", cadence: "cadence.com", siemens_eda: "eda.sw.siemens.com",
  nvidia: "nvidia.com", amd: "amd.com", qualcomm: "qualcomm.com", apple: "apple.com", mediatek: "mediatek.com", hisilicon: "hisilicon.com",
  shinetsu: "shinetsu.co.jp", sumco: "sumcosi.com", globalwafers: "sas-globalwafers.com", jsr: "jsr.co.jp", tok: "tok.co.jp",
  linde: "linde.com", airliquide: "airliquide.com", ibiden: "ibiden.com", unimicron: "unimicron.com",
  asml: "asml.com", nikon: "nikon.com", canon: "global.canon", amat: "appliedmaterials.com", tel: "tel.com", lam: "lamresearch.com", kla: "kla.com",
  tsmc: "tsmc.com", samsung: "samsung.com", intel: "intel.com", rapidus: "rapidus.inc", smic: "smics.com", umc: "umc.com",
  gf: "gf.com", ti: "ti.com", infineon: "infineon.com", st: "st.com", tower: "towersemi.com",
  skhynix: "skhynix.com", micron: "micron.com", ymtc: "ymtc.com", cxmt: "cxmt.com", kioxia: "kioxia.com",
  ase: "aseglobal.com", amkor: "amkor.com", jcet: "jcetglobal.com", foxconn: "foxconn.com",
  ibm_res: "ibm.com", leti: "leti-cea.fr", ansys: "ansys.com", empyrean: "empyrean.com.cn", broadcom: "broadcom.com", marvell: "marvell.com", unisoc: "unisoc.com",
  sksiltron: "sksiltron.com", siltronic: "siltronic.com", nsig: "nsig.com.cn", sumitomo_chem: "sumitomo-chem.co.jp", dupont: "dupont.com",
  resonac: "resonac.com", tnsc: "tn-sanso.co.jp", airproducts: "airproducts.com", skmaterials: "sk-inc.com",
  shinko: "shinko.co.jp", samsungem: "samsungsem.com", ats: "ats.net", asmi: "asm.com", kokusai: "kokusai-electric.com",
  naura: "naura.com", amec: "amec-inc.com", hitachiht: "hitachi-hightech.com", ebara: "ebara.com", entegris: "entegris.com",
  onto: "ontoinnovation.com", nova: "novami.com", huahong: "huahonggrace.com", vis: "vis.com.tw", nexchip: "nexchip.com.cn",
  sonysemi: "sony-semicon.com", renesas: "renesas.com", bosch: "bosch.com", nanya: "nanya.com", winbond: "winbond.com",
  google: "google.com", amazon: "amazon.com", cambricon: "cambricon.com", biren: "birentech.com",
  onsemi: "onsemi.com", adi: "analog.com", nxp: "nxp.com", microchip: "microchip.com",
  spil: "spil.com.tw", pti: "pti.com.tw", utac: "utacgroup.com", kyec: "kyec.com.tw", inari: "inari-amertron.com",
  quanta: "quantatw.com", wistron: "wistron.com", supermicro: "supermicro.com", luxshare: "luxshare-ict.com",
  microsoft: "microsoft.com", meta: "meta.com", alibaba: "alibabacloud.com", tesla: "tesla.com", denso: "denso.com", vw: "volkswagen-group.com",
  xiaomi: "xiaomi.com", lenovo: "lenovo.com", hp: "hp.com",
};

export const CUSTOMERS = {
  asml: [["tsmc", 0.35], ["samsung", 0.25], ["intel", 0.2], ["skhynix", 0.08], ["micron", 0.05]],
  nikon: [["intel", 0.2], ["smic", 0.15], ["umc", 0.1]],
  canon: [["smic", 0.2], ["ymtc", 0.12], ["umc", 0.1]],
  amat: [["tsmc", 0.3], ["samsung", 0.25], ["intel", 0.12], ["skhynix", 0.1], ["micron", 0.08], ["smic", 0.05]],
  lam: [["samsung", 0.3], ["tsmc", 0.22], ["skhynix", 0.18], ["micron", 0.12], ["smic", 0.06]],
  tel: [["tsmc", 0.3], ["samsung", 0.25], ["skhynix", 0.12], ["micron", 0.08], ["rapidus", 0.05]],
  kla: [["tsmc", 0.35], ["samsung", 0.2], ["intel", 0.15], ["skhynix", 0.1]],
  shinetsu: [["tsmc", 0.3], ["samsung", 0.22], ["skhynix", 0.12], ["micron", 0.1], ["umc", 0.06], ["smic", 0.05]],
  sumco: [["tsmc", 0.28], ["samsung", 0.25], ["micron", 0.12], ["skhynix", 0.1]],
  globalwafers: [["tsmc", 0.25], ["umc", 0.15], ["gf", 0.12], ["st", 0.08]],
  jsr: [["tsmc", 0.3], ["samsung", 0.25], ["intel", 0.12], ["skhynix", 0.1]],
  tok: [["tsmc", 0.28], ["samsung", 0.22], ["skhynix", 0.12], ["smic", 0.08]],
  linde: [["tsmc", 0.2], ["samsung", 0.18], ["intel", 0.12], ["skhynix", 0.08], ["micron", 0.06]],
  airliquide: [["tsmc", 0.22], ["samsung", 0.15], ["st", 0.1], ["infineon", 0.08]],
  ibiden: [["intel", 0.3], ["nvidia", 0.2], ["tsmc", 0.15], ["amd", 0.12]],
  unimicron: [["nvidia", 0.25], ["amd", 0.15], ["mediatek", 0.12], ["intel", 0.1]],
  synopsys: [["nvidia", 0.12], ["apple", 0.1], ["qualcomm", 0.1], ["intel", 0.08], ["samsung", 0.08]],
  cadence: [["nvidia", 0.12], ["apple", 0.1], ["mediatek", 0.08], ["amd", 0.08]],
  siemens_eda: [["infineon", 0.15], ["st", 0.1], ["intel", 0.08]],
  arm: [["apple", 0.16], ["qualcomm", 0.14], ["mediatek", 0.12], ["samsung", 0.08], ["nvidia", 0.06]],
  imec: [["asml", 0.15], ["tsmc", 0.12], ["intel", 0.1], ["samsung", 0.1]],
  tsmc: [["nvidia", 0.19], ["apple", 0.17], ["amd", 0.1], ["qualcomm", 0.08], ["mediatek", 0.07], ["intel", 0.04]],
  samsung: [["nvidia", 0.12], ["qualcomm", 0.08], ["apple", 0.06]],
  skhynix: [["nvidia", 0.3], ["amd", 0.08]],
  micron: [["nvidia", 0.15], ["apple", 0.08], ["amd", 0.05]],
  smic: [["hisilicon", 0.25], ["qualcomm", 0.08]],
  umc: [["mediatek", 0.15], ["infineon", 0.06], ["ti", 0.05]],
  gf: [["amd", 0.12], ["qualcomm", 0.1], ["infineon", 0.05]],
  ymtc: [["hisilicon", 0.2]],
  cxmt: [["hisilicon", 0.1]],
  ase: [["apple", 0.15], ["nvidia", 0.12], ["amd", 0.1], ["qualcomm", 0.1], ["mediatek", 0.08]],
  amkor: [["apple", 0.18], ["nvidia", 0.1], ["qualcomm", 0.1], ["infineon", 0.06]],
  jcet: [["hisilicon", 0.15], ["qualcomm", 0.1], ["mediatek", 0.08]],
  intel: [["foxconn", 0.15]],
  nvidia: [["microsoft", 0.2], ["meta", 0.12], ["amazon", 0.1], ["google", 0.08], ["foxconn", 0.15]],
  amd: [["foxconn", 0.2]],
  apple: [["foxconn", 0.38]],
  qualcomm: [["foxconn", 0.2]],
  mediatek: [["foxconn", 0.25]],
  hisilicon: [["foxconn", 0.1]],
  st: [["apple", 0.12], ["foxconn", 0.08]],
  ti: [["foxconn", 0.08]],
  infineon: [["foxconn", 0.06]],
  broadcom: [["apple", 0.2], ["google", 0.15], ["meta", 0.1]],
  marvell: [["amazon", 0.15], ["microsoft", 0.1]],
  asmi: [["tsmc", 0.3], ["samsung", 0.2], ["intel", 0.12], ["skhynix", 0.08]],
  kokusai: [["samsung", 0.25], ["tsmc", 0.15], ["micron", 0.1], ["skhynix", 0.1]],
  naura: [["smic", 0.3], ["huahong", 0.15], ["ymtc", 0.12], ["nexchip", 0.08]],
  amec: [["smic", 0.25], ["ymtc", 0.12], ["huahong", 0.1], ["tsmc", 0.1]],
  ebara: [["tsmc", 0.25], ["samsung", 0.2], ["intel", 0.1]],
  entegris: [["tsmc", 0.22], ["samsung", 0.18], ["intel", 0.1], ["micron", 0.08]],
  hitachiht: [["tsmc", 0.2], ["samsung", 0.15], ["skhynix", 0.1]],
  onto: [["tsmc", 0.2], ["samsung", 0.15], ["micron", 0.1]],
  nova: [["tsmc", 0.3], ["samsung", 0.15]],
  shinko: [["intel", 0.3], ["tsmc", 0.12], ["amd", 0.1]],
  samsungem: [["samsung", 0.35], ["qualcomm", 0.08]],
  ats: [["amd", 0.15], ["nvidia", 0.1], ["intel", 0.1]],
  sksiltron: [["samsung", 0.3], ["skhynix", 0.25], ["tsmc", 0.1]],
  siltronic: [["infineon", 0.12], ["st", 0.1], ["tsmc", 0.1], ["samsung", 0.1]],
  sumitomo_chem: [["tsmc", 0.25], ["samsung", 0.2], ["skhynix", 0.1]],
  dupont: [["intel", 0.15], ["tsmc", 0.15], ["micron", 0.1]],
  resonac: [["tsmc", 0.2], ["samsung", 0.15], ["skhynix", 0.1]],
  tnsc: [["tsmc", 0.2], ["samsung", 0.15]],
  airproducts: [["tsmc", 0.18], ["samsung", 0.15], ["intel", 0.12], ["micron", 0.08]],
  skmaterials: [["skhynix", 0.35], ["samsung", 0.2]],
  spil: [["apple", 0.12], ["mediatek", 0.12], ["nvidia", 0.08]],
  pti: [["micron", 0.2], ["skhynix", 0.12]],
  utac: [["ti", 0.12], ["infineon", 0.1], ["st", 0.08]],
  kyec: [["mediatek", 0.15], ["nvidia", 0.08]],
  inari: [["broadcom", 0.3]],
  quanta: [["microsoft", 0.2], ["meta", 0.12], ["amazon", 0.1], ["google", 0.08]],
  wistron: [["microsoft", 0.1], ["amazon", 0.08]],
  supermicro: [["meta", 0.1], ["microsoft", 0.08]],
  luxshare: [["apple", 0.6]],
  sonysemi: [["apple", 0.4], ["xiaomi", 0.08]],
  renesas: [["denso", 0.2], ["bosch", 0.08]],
  onsemi: [["tesla", 0.12], ["bosch", 0.08], ["vw", 0.06]],
  adi: [["apple", 0.1], ["tesla", 0.06]],
  nxp: [["bosch", 0.1], ["vw", 0.08], ["tesla", 0.05]],
  huahong: [["hisilicon", 0.1]],
};

export const POLICIES = [
  { id: "bis", name: "U.S. BIS AI-chip & SME export controls", sev: 9, stages: ["logic_ai", "hbm", "adv_fab", "litho", "depo", "etch", "metro"] },
  { id: "nl", name: "Dutch lithography export licensing", sev: 8, stages: ["litho"] },
  { id: "meti", name: "Japan METI equipment & material controls", sev: 6, stages: ["depo", "etch", "resist", "metro"] },
  { id: "cnmat", name: "China Ga/Ge/graphite export licensing", sev: 7, stages: ["gases", "analog", "wafers"] },
  { id: "chips", name: "CHIPS Act / EU Chips Act incentives", sev: 4, stages: ["adv_fab", "mature_fab", "memory_fab"] },
  { id: "twp", name: "Taiwan core-technology protection rules", sev: 5, stages: ["adv_fab", "adv_pkg"] },
  { id: "tariff", name: "Section-301 / retaliatory tariffs", sev: 4, stages: ["mature_fab", "systems", "m_consumer", "m_auto"] },
];

export const EVENTS = [
  { id: "e1", date: "Jul 03", daysAgo: 3, sev: 8, type: "Export Control", conf: "High",
    title: "U.S. expands AI-chip export-control rules",
    summary: "New BIS rules widen licensing requirements for top-end AI accelerators and certain HBM stacks shipped to China.",
    stages: ["logic_ai", "hbm", "adv_fab", "adv_pkg"], countries: ["us", "cn", "tw", "kr"],
    first: "Chinese firms face tighter access to leading-edge AI chips and HBM.",
    second: "Demand shifts to domestic substitutes; pressure on Huawei/SMIC roadmap; retaliation risk via materials.",
    watch: "Final BIS rule text · NVIDIA/AMD guidance · Chinese policy response",
    detail: "The interim final rule extends license requirements from training-class accelerators to a performance-density band capturing several previously exportable inference parts, and for the first time places certain HBM3E-class memory stacks under the same regime. A 30-day comment window applies; enforcement guidance suggests presumption of denial for named Chinese entities.",
    source: "Federal Register · BIS interim final rule (official) + two trade-press confirmations",
    timeline: [["Jul 01", "Draft rule reported by trade press (conf: Low)"], ["Jul 03", "Interim final rule published (conf: High)"], ["Aug 02", "Expected effective date after comment window"]] },
  { id: "e2", date: "Jul 02", daysAgo: 4, sev: 4, type: "Technology Update", conf: "Medium",
    title: "TSMC accelerates CoWoS capacity expansion",
    summary: "Reported pull-in of advanced-packaging capacity targets on sustained AI accelerator demand.",
    stages: ["adv_pkg", "logic_ai"], countries: ["tw"],
    first: "Advanced-packaging bottleneck eases into 2027.",
    second: "Relieves HBM-attach constraints; pricing pressure on ASE/Amkor; substrate order growth.",
    watch: "Monthly CoWoS run-rate estimates · ABF substrate guidance",
    detail: "Supply-chain checks point to a pull-forward of 2027 CoWoS-L capacity targets into late 2026, driven by sustained multi-year accelerator commitments. Not confirmed by company IR; magnitude estimates vary ±2 months across sources.",
    source: "Taiwan supply-chain press + component-order checks (unconfirmed by TSMC IR)",
    timeline: [["Jun 20", "Substrate suppliers report expanded 2026 forecasts"], ["Jul 02", "Capacity pull-in reported by two independent outlets"]] },
  { id: "e3", date: "Jun 30", daysAgo: 6, sev: 6, type: "Geopolitical Risk", conf: "Medium",
    title: "Elevated military activity around Taiwan Strait",
    summary: "Increased exercise tempo raises baseline geopolitical risk for the Taiwan cluster.",
    stages: ["adv_fab", "adv_pkg", "osat"], countries: ["tw", "cn", "us"],
    first: "No supply disruption; insurance and logistics premiums rise.",
    second: "Customer pressure for diversification; tailwind for U.S./Japan fab projects.",
    watch: "PLA exercise announcements · TSMC Arizona/Kumamoto ramp commentary",
    detail: "Exercise tempo around the median line has risen above its 12-month average for a second consecutive week. No interference with commercial shipping or airfreight observed; the effect is on risk pricing (war-risk insurance, diversification pressure), not physical flows.",
    source: "Taiwan MND daily activity reports (official) + shipping-insurance market data",
    timeline: [["Jun 24", "Exercise tempo rises above 12-month average"], ["Jun 30", "Second consecutive week elevated; insurers reprice"]] },
  { id: "e4", date: "Jun 27", daysAgo: 9, sev: 7, type: "Critical Material Risk", conf: "High",
    title: "China tightens gallium / germanium licensing",
    summary: "Slower export-license approvals for Ga/Ge compounds used in power and RF semiconductors.",
    stages: ["gases", "analog"], countries: ["cn", "jp", "de", "fr"],
    first: "Price rises and longer lead times for compound-semiconductor inputs.",
    second: "Accelerated non-China sourcing; signals material leverage in tech disputes.",
    watch: "License approval rates · Ga/Ge spot prices · MOFCOM statements",
    detail: "Approval times for gallium and germanium compound export licenses have lengthened from ~45 to ~75 days per importer reports, without a formal rule change — an administrative-throttling pattern consistent with earlier episodes. Spot prices are up double digits since the slowdown began.",
    source: "MOFCOM notices (official) + importer surveys + customs statistics",
    timeline: [["Jun 10", "Importers report first approval delays"], ["Jun 27", "Delays confirmed across multiple buyers; prices move (conf: High)"]] },
  { id: "e5", date: "Jun 25", daysAgo: 11, sev: 5, type: "Company Guidance", conf: "Medium",
    title: "Major memory maker trims 2026 capex",
    summary: "Guidance revision shifts spend from legacy DRAM toward HBM lines.",
    stages: ["memory_fab", "depo", "etch"], countries: ["kr", "us", "jp"],
    first: "Equipment makers exposed to legacy DRAM see order softness.",
    second: "HBM concentration deepens; legacy DRAM pricing firms.",
    watch: "Equipment book-to-bill · DRAM contract pricing",
    detail: "The revision cuts legacy-DRAM wafer-fab equipment spend while re-allocating to HBM TSV and advanced-packaging lines — net capex roughly flat, mix radically different. Equipment exposure splits: legacy-DRAM deposition/etch softens, bonder and TSV toolmakers benefit.",
    source: "Company guidance call transcript + sell-side capex trackers",
    timeline: [["Jun 25", "Guidance revision on quarterly call"], ["Jul 01", "Equipment suppliers acknowledge order pushouts"]] },
  { id: "e6", date: "Jun 24", daysAgo: 12, sev: 3, type: "Policy Signal", conf: "Medium",
    title: "Japan approves next Rapidus funding tranche",
    summary: "Additional subsidies for 2nm pilot line and packaging R&D.",
    stages: ["adv_fab", "depo", "resist"], countries: ["jp"],
    first: "Japan's advanced-node ambitions gain credibility.",
    second: "Long-run diversification of leading-edge capacity away from Taiwan cluster.",
    watch: "Rapidus pilot yields · METI budget details · customer commitments",
    detail: "The tranche funds the 2nm pilot line's second phase and a new advanced-packaging R&D consortium, conditional on pilot-yield milestones. Cumulative public support now exceeds ¥1.7T; first customer commitments remain the key open question.",
    source: "METI budget announcement (official) + Rapidus press release",
    timeline: [["Jun 24", "Tranche approved by METI"], ["H2 2026", "Pilot-yield milestone review"]] },
];

export const SCENARIOS = [
  { id: "none", name: "Baseline", desc: "Current sample state. No simulated shock applied." },
  { id: "strait", name: "Taiwan Strait crisis", desc: "Blockade-level disruption injected as a severity-10 simulated event.",
    event: { sev: 10, daysAgo: 0, conf: "Simulated", stages: ["adv_fab", "adv_pkg", "osat", "substrates"], countries: ["tw", "cn"] } },
  { id: "materials", name: "China materials ban", desc: "Hard export ban on Ga/Ge and rare-earth inputs (severity 9).",
    event: { sev: 9, daysAgo: 0, conf: "Simulated", stages: ["gases", "wafers", "analog"], countries: ["cn", "jp", "de", "fr"] } },
  { id: "exportmax", name: "Export controls max", desc: "Controls extended to sub-leading-edge tools and cloud access (severity 8).",
    event: { sev: 8, daysAgo: 0, conf: "Simulated", stages: ["litho", "depo", "etch", "metro", "logic_ai", "memory_fab"], countries: ["cn", "nl", "jp", "us"] } },
];

export const OWNERS = {
  tsmc: [["Taiwan NDF (gov)", 0.0638], ["BlackRock", 0.051], ["GIC (Singapore gov)", 0.032], ["Vanguard", 0.039]],
  asml: [["Vanguard", 0.089], ["BlackRock", 0.08], ["Capital Group", 0.07], ["Baillie Gifford", 0.025]],
  nvidia: [["Vanguard", 0.087], ["BlackRock", 0.075], ["Fidelity (FMR)", 0.05], ["State Street", 0.04]],
  samsung: [["Lee family & affiliates", 0.18], ["Korea NPS (gov)", 0.07], ["BlackRock", 0.05]],
  skhynix: [["SK Square (chaebol)", 0.205], ["Korea NPS (gov)", 0.08], ["BlackRock", 0.05]],
  intel: [["US Treasury/CHIPS equity (gov)", 0.099], ["Vanguard", 0.085], ["BlackRock", 0.075], ["Nvidia", 0.041], ["SoftBank", 0.015]],
  micron: [["Vanguard", 0.085], ["BlackRock", 0.075], ["State Street", 0.04]],
  amd: [["Vanguard", 0.09], ["BlackRock", 0.075], ["Fidelity (FMR)", 0.05]],
  apple: [["Vanguard", 0.0947], ["BlackRock", 0.0768], ["State Street", 0.0402], ["Berkshire Hathaway", 0.02]],
  qualcomm: [["Vanguard", 0.09], ["BlackRock", 0.08]],
  broadcom: [["Vanguard", 0.095], ["BlackRock", 0.08], ["State Street", 0.04]],
  amat: [["BlackRock", 0.082], ["Vanguard", 0.075], ["State Street", 0.04]],
  lam: [["BlackRock", 0.098], ["Vanguard", 0.095], ["State Street", 0.046]],
  kla: [["Vanguard", 0.095], ["BlackRock", 0.08]],
  arm: [["SoftBank Group", 0.9], ["Vanguard", 0.01]],
  smic: [["China Big Fund (gov)", 0.15], ["Datang (SOE)", 0.126], ["Shanghai IC Industry Fund (gov)", 0.115]],
  ymtc: [["Hubei Changsheng Development (gov)", 0.3], ["National Big Fund I+II (gov)", 0.122]],
  tel: [["Master Trust Bank of Japan (nominee)", 0.254], ["Custody Bank of Japan (nominee)", 0.092], ["Vanguard", 0.072], ["BlackRock", 0.065]],
  shinetsu: [["Nomura AM", 0.05], ["BlackRock", 0.05]],
  rapidus: [["NEDO / Japan govt (golden share)", 0.115], ["Consortium of 32 Japanese firms (Toyota, Sony, SoftBank, Kioxia, NTT, NEC, MUFG, others)", 0.885]],
  hisilicon: [["Huawei (private)", 1.0]],
  microsoft: [["Vanguard", 0.09], ["BlackRock", 0.072], ["Steven Ballmer", 0.045]],
  google: [["Founders — voting power via Class B (economic ~11.5%)", 0.527], ["Vanguard", 0.07]],
  meta: [["Zuckerberg — voting power via Class B (economic ~13.5%)", 0.61], ["Vanguard", 0.075]],
  foxconn: [["Terry Gou & family (declining)", 0.05], ["Vanguard", 0.03]],
  ti: [["Vanguard", 0.1061], ["BlackRock", 0.0552]],
  infineon: [["BlackRock", 0.06], ["Vanguard", 0.04]],
};
